// Code generated by ent, DO NOT EDIT.

package pairing

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pairing type in the database.
	Label = "pairing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldLeadID holds the string denoting the lead_id field in the database.
	FieldLeadID = "lead_id"
	// FieldFollowID holds the string denoting the follow_id field in the database.
	FieldFollowID = "follow_id"
	// EdgeLead holds the string denoting the lead edge name in mutations.
	EdgeLead = "lead"
	// EdgeFollow holds the string denoting the follow edge name in mutations.
	EdgeFollow = "follow"
	// Table holds the table name of the pairing in the database.
	Table = "pairing"
	// LeadTable is the table that holds the lead relation/edge.
	LeadTable = "pairing"
	// LeadInverseTable is the table name for the Robot entity.
	// It exists in this package in order to avoid circular dependency with the "robot" package.
	LeadInverseTable = "robot"
	// LeadColumn is the table column denoting the lead relation/edge.
	LeadColumn = "lead_id"
	// FollowTable is the table that holds the follow relation/edge.
	FollowTable = "pairing"
	// FollowInverseTable is the table name for the Robot entity.
	// It exists in this package in order to avoid circular dependency with the "robot" package.
	FollowInverseTable = "robot"
	// FollowColumn is the table column denoting the follow relation/edge.
	FollowColumn = "follow_id"
)

// Columns holds all SQL columns for pairing fields.
var Columns = []string{
	FieldID,
	FieldDateCreated,
	FieldLeadID,
	FieldFollowID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Pairing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByLeadID orders the results by the lead_id field.
func ByLeadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeadID, opts...).ToFunc()
}

// ByFollowID orders the results by the follow_id field.
func ByFollowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFollowID, opts...).ToFunc()
}

// ByLeadField orders the results by lead field.
func ByLeadField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLeadStep(), sql.OrderByField(field, opts...))
	}
}

// ByFollowField orders the results by follow field.
func ByFollowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFollowStep(), sql.OrderByField(field, opts...))
	}
}
func newLeadStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LeadInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LeadTable, LeadColumn),
	)
}
func newFollowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FollowInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, FollowTable, FollowColumn),
	)
}
