edition = "2023";

package app;

import "google/protobuf/timestamp.proto";
import "orm.proto";
import "payday.proto";

option features.field_presence = IMPLICIT;
option go_package = "github.com/lesomnus/payday/internal/apptest";

// Tenant is the wall this app is divided by.
message Tenant {
  bytes id = 1 [(orm.field) = {
    type: TYPE_UUID
    key: true
    default: ""
  }];
  string alias = 4 [(orm.field) = {unique: true}];

  google.protobuf.Timestamp date_created = 15 [(orm.field) = {
    immutable: true
    default: ""
  }];

  option (orm.message) = {rpc: {crud: true}};
  option (payday.entity) = {
    domain: 1
    tenant: {}
  };
}
