// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/payday/holder.proto

package schema

import (
	uuid "github.com/google/uuid"
	apptest "github.com/lesomnus/payday/internal/apptest"
	ent "github.com/protobuf-orm/ent"
	dialect "github.com/protobuf-orm/ent/dialect"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	edge "github.com/protobuf-orm/ent/schema/edge"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
	entpb "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpb"
)

type Holder struct {
	ent.Schema
}

func (Holder) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Unique().
			Immutable(),
		field.String("alias"),
		field.String("name"),
		field.String("desc"),
		field.JSON("labels", map[string]string{}).
			Optional(),
		field.Time("date_updated"),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.String("idp_subject"),
		field.String("profile").GoType(&apptest.Profile{}).ValueScanner(entpb.ValueScanner[*apptest.Profile]{}).SchemaType(map[string]string{dialect.Postgres: "jsonb", dialect.MySQL: "json"}).
			Optional(),
		field.UUID("tenant_id", uuid.UUID{}).
			Immutable(),
	}
}

func (Holder) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Field("tenant_id").
			Required().
			Immutable(),
	}
}

func (Holder) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("alias").
			Edges("tenant").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
	}
}

func (Holder) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "holder"},
	}
}
