// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: shared/thing.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	field "github.com/protobuf-orm/ent/schema/field"
)

type Thing struct {
	ent.Schema
}

func (Thing) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("alias"),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
	}
}

func (Thing) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "thing"},
	}
}
