// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: shared/thing.proto

package schema

import (
	ent "entgo.io/ent"
	entsql "entgo.io/ent/dialect/entsql"
	schema "entgo.io/ent/schema"
	field "entgo.io/ent/schema/field"
	uuid "github.com/google/uuid"
)

type Thing struct {
	ent.Schema
}

func (Thing) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Unique().
			Immutable(),
		field.String("alias"),
		field.Time("date_erased").
			Nillable().
			Optional(),
	}
}

func (Thing) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "thing"},
	}
}
