// Code generated by ent, DO NOT EDIT.

package reading

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the reading type in the database.
	Label = "reading"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldTenantId holds the string denoting the tenant_id field in the database.
	FieldTenantId = "tenant_id"
	// FieldCelsius holds the string denoting the celsius field in the database.
	FieldCelsius = "celsius"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldRobotId holds the string denoting the robot_id field in the database.
	FieldRobotId = "robot_id"
	// EdgeRobot holds the string denoting the robot edge name in mutations.
	EdgeRobot = "robot"
	// Table holds the table name of the reading in the database.
	Table = "reading"
	// RobotTable is the table that holds the robot relation/edge.
	RobotTable = "reading"
	// RobotInverseTable is the table name for the Robot entity.
	// It exists in this package in order to avoid circular dependency with the "robot" package.
	RobotInverseTable = "robot"
	// RobotColumn is the table column denoting the robot relation/edge.
	RobotColumn = "robot_id"
)

// Columns holds all SQL columns for reading fields.
var Columns = []string{
	FieldId,
	FieldTenantId,
	FieldCelsius,
	FieldDateCreated,
	FieldRobotId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Reading queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByTenantId orders the results by the tenant_id field.
func ByTenantId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantId, opts...).ToFunc()
}

// ByCelsius orders the results by the celsius field.
func ByCelsius(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCelsius, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByRobotId orders the results by the robot_id field.
func ByRobotId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRobotId, opts...).ToFunc()
}

// ByRobotField orders the results by robot field.
func ByRobotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRobotStep(), sql.OrderByField(field, opts...))
	}
}
func newRobotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(RobotInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, RobotTable, RobotColumn),
	)
}
