// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payday/app.proto

package pdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// App says that this file's proto package is the app's own.
//
// # What it is for
//
// payday has to know one package per app: its own entities -- the tenant, the
// holder, the trail, the queue -- are **copied into it**, so that a caller says
// `acme.Tenant` rather than the name of the framework the app was built with,
// and `pd entity add` writes a new entity there.
//
// Ordinarily nothing says which, because there is only one and payday reads it
// off the schema. An app that declares a second package has to say, and this is
// how:
//
//	edition = "2023";
//
//	package acme;
//
//	option (payday.app) = {};
//
// # Why an app would have two
//
// Because a name can be worth more than the app that holds it. A fleet that
// runs several services may want one word for the thing they are all about --
// `hday.oasys.Robot` -- while everything each service keeps for itself stays in
// a package of its own. The shared message is then the same name everywhere it
// is read, and nothing else has to be.
//
// This is presence and nothing else: a file either says it or does not. It is a
// message rather than a `bool` so that something can be added to it later
// without every app that set it having to change.
//
// Setting it on more than one package is refused. Two answers to "where do
// payday's entities go" is the thing this exists to avoid, and getting two of
// them from the option meant to settle it would be worse than getting none.
type App struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_payday_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_payday_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type App_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 App_builder) Build() *App {
	m0 := &App{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_payday_app_proto protoreflect.FileDescriptor

const file_payday_app_proto_rawDesc = "" +
	"\n" +
	"\x10payday/app.proto\x12\x06payday\"\x05\n" +
	"\x03AppB&Z\x1fgithub.com/lesomnus/payday/pdpb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_payday_app_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_payday_app_proto_goTypes = []any{
	(*App)(nil), // 0: payday.App
}
var file_payday_app_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payday_app_proto_init() }
func file_payday_app_proto_init() {
	if File_payday_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payday_app_proto_rawDesc), len(file_payday_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payday_app_proto_goTypes,
		DependencyIndexes: file_payday_app_proto_depIdxs,
		MessageInfos:      file_payday_app_proto_msgTypes,
	}.Build()
	File_payday_app_proto = out.File
	file_payday_app_proto_goTypes = nil
	file_payday_app_proto_depIdxs = nil
}
