// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payday/batch.proto

package pdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ops *[]*Op                 `protobuf:"bytes,1,rep,name=ops"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_payday_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payday_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchRequest) GetOps() []*Op {
	if x != nil {
		if x.xxx_hidden_Ops != nil {
			return *x.xxx_hidden_Ops
		}
	}
	return nil
}

func (x *BatchRequest) SetOps(v []*Op) {
	x.xxx_hidden_Ops = &v
}

type BatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The operations, run in the order they are written, in one transaction.
	//
	// The order is the caller's to get right and the server does not sort it: an
	// operation that refers to a row an earlier one wrote has to come after it,
	// and nothing here can work out which those are.
	Ops []*Op
}

func (b0 BatchRequest_builder) Build() *BatchRequest {
	m0 := &BatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ops = &b.Ops
	return m0
}

type Op struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Method  string                 `protobuf:"bytes,1,opt,name=method"`
	xxx_hidden_Request *anypb.Any             `protobuf:"bytes,2,opt,name=request"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_payday_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_payday_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Op) GetMethod() string {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return ""
}

func (x *Op) GetRequest() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Request
	}
	return nil
}

func (x *Op) SetMethod(v string) {
	x.xxx_hidden_Method = v
}

func (x *Op) SetRequest(v *anypb.Any) {
	x.xxx_hidden_Request = v
}

func (x *Op) HasRequest() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Request != nil
}

func (x *Op) ClearRequest() {
	x.xxx_hidden_Request = nil
}

type Op_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The RPC, by the name gRpc knows it by: "/app.RobotService/Add".
	Method string
	// The request, packed. Its type has to be what `method` takes -- an `Any`
	// carrying anything else is refused rather than coerced, since a request that
	// decoded into a different message would be a write the caller did not ask
	// for.
	Request *anypb.Any
}

func (b0 Op_builder) Build() *Op {
	m0 := &Op{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_Request = b.Request
	return m0
}

type BatchResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Results *[]*anypb.Any          `protobuf:"bytes,1,rep,name=results"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_payday_batch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payday_batch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchResponse) GetResults() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Results != nil {
			return *x.xxx_hidden_Results
		}
	}
	return nil
}

func (x *BatchResponse) SetResults(v []*anypb.Any) {
	x.xxx_hidden_Results = &v
}

type BatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// One answer per operation, in the same order.
	//
	// There is no per-operation error here and that is not an omission: the whole
	// batch is one transaction, so an operation that refused means none of them
	// happened, and there is nothing to report per operation because there is
	// nothing to report. The refusal is the RPC's error, and it says which
	// operation it was about.
	Results []*anypb.Any
}

func (b0 BatchResponse_builder) Build() *BatchResponse {
	m0 := &BatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Results = &b.Results
	return m0
}

var File_payday_batch_proto protoreflect.FileDescriptor

const file_payday_batch_proto_rawDesc = "" +
	"\n" +
	"\x12payday/batch.proto\x12\x06payday\x1a\x19google/protobuf/any.proto\",\n" +
	"\fBatchRequest\x12\x1c\n" +
	"\x03ops\x18\x01 \x03(\v2\n" +
	".payday.OpR\x03ops\"L\n" +
	"\x02Op\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12.\n" +
	"\arequest\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\arequest\"?\n" +
	"\rBatchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\aresults2A\n" +
	"\fBatchService\x121\n" +
	"\x02Do\x12\x14.payday.BatchRequest\x1a\x15.payday.BatchResponseB&Z\x1fgithub.com/lesomnus/payday/pdpb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_payday_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payday_batch_proto_goTypes = []any{
	(*BatchRequest)(nil),  // 0: payday.BatchRequest
	(*Op)(nil),            // 1: payday.Op
	(*BatchResponse)(nil), // 2: payday.BatchResponse
	(*anypb.Any)(nil),     // 3: google.protobuf.Any
}
var file_payday_batch_proto_depIdxs = []int32{
	1, // 0: payday.BatchRequest.ops:type_name -> payday.Op
	3, // 1: payday.Op.request:type_name -> google.protobuf.Any
	3, // 2: payday.BatchResponse.results:type_name -> google.protobuf.Any
	0, // 3: payday.BatchService.Do:input_type -> payday.BatchRequest
	2, // 4: payday.BatchService.Do:output_type -> payday.BatchResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payday_batch_proto_init() }
func file_payday_batch_proto_init() {
	if File_payday_batch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payday_batch_proto_rawDesc), len(file_payday_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payday_batch_proto_goTypes,
		DependencyIndexes: file_payday_batch_proto_depIdxs,
		MessageInfos:      file_payday_batch_proto_msgTypes,
	}.Build()
	File_payday_batch_proto = out.File
	file_payday_batch_proto_goTypes = nil
	file_payday_batch_proto_depIdxs = nil
}
