// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payday.proto

package pdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_payday_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Entity)(nil),
		Field:         46001,
		Name:          "payday.entity",
		Tag:           "bytes,46001,opt,name=entity",
		Filename:      "payday.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional payday.Entity entity = 46001;
	E_Entity = &file_payday_proto_extTypes[0]
)

var File_payday_proto protoreflect.FileDescriptor

const file_payday_proto_rawDesc = "" +
	"\n" +
	"\fpayday.proto\x12\x06payday\x1a google/protobuf/descriptor.proto\x1a\x13payday/entity.proto:I\n" +
	"\x06entity\x12\x1f.google.protobuf.MessageOptions\x18\xb1\xe7\x02 \x01(\v2\x0e.payday.EntityR\x06entityB!Z\x1fgithub.com/lesomnus/payday/pdpbb\beditionsp\xe8\a"

var file_payday_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*Entity)(nil),                      // 1: payday.Entity
}
var file_payday_proto_depIdxs = []int32{
	0, // 0: payday.entity:extendee -> google.protobuf.MessageOptions
	1, // 1: payday.entity:type_name -> payday.Entity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payday_proto_init() }
func file_payday_proto_init() {
	if File_payday_proto != nil {
		return
	}
	file_payday_entity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payday_proto_rawDesc), len(file_payday_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_payday_proto_goTypes,
		DependencyIndexes: file_payday_proto_depIdxs,
		ExtensionInfos:    file_payday_proto_extTypes,
	}.Build()
	File_payday_proto = out.File
	file_payday_proto_goTypes = nil
	file_payday_proto_depIdxs = nil
}
