// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payday/token.proto

package pdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenIntrospectRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token string                 `protobuf:"bytes,1,opt,name=token"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenIntrospectRequest) Reset() {
	*x = TokenIntrospectRequest{}
	mi := &file_payday_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIntrospectRequest) ProtoMessage() {}

func (x *TokenIntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payday_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokenIntrospectRequest) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *TokenIntrospectRequest) SetToken(v string) {
	x.xxx_hidden_Token = v
}

type TokenIntrospectRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The token, exactly as it arrived.
	//
	// A secret in a request body, which is what it has to be: the whole question
	// is what this string means, and the store cannot answer it from a hash the
	// caller computed -- the parameters would be the caller's, and a store cannot
	// vouch for those. It is the same trade `VouchService` makes for a password
	// and is why both are refused over cleartext.
	Token string
}

func (b0 TokenIntrospectRequest_builder) Build() *TokenIntrospectRequest {
	m0 := &TokenIntrospectRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

// TokenIntrospectResponse is `auth.Identity` as it crosses.
//
// Every field here fills one there, and the one field of `auth.Identity` that
// is missing is `Method`: how a caller authenticated is answered by whatever
// read the credential, and a store that could name it would be naming the
// wrong process's answer.
type TokenIntrospectResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id       []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_TenantId []byte                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_Tenant   string                 `protobuf:"bytes,3,opt,name=tenant"`
	xxx_hidden_Alias    string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Grant    *Grant                 `protobuf:"bytes,5,opt,name=grant"`
	xxx_hidden_Expires  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TokenIntrospectResponse) Reset() {
	*x = TokenIntrospectResponse{}
	mi := &file_payday_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIntrospectResponse) ProtoMessage() {}

func (x *TokenIntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payday_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokenIntrospectResponse) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *TokenIntrospectResponse) GetTenantId() []byte {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return nil
}

func (x *TokenIntrospectResponse) GetTenant() string {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return ""
}

func (x *TokenIntrospectResponse) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *TokenIntrospectResponse) GetGrant() *Grant {
	if x != nil {
		return x.xxx_hidden_Grant
	}
	return nil
}

func (x *TokenIntrospectResponse) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Expires
	}
	return nil
}

func (x *TokenIntrospectResponse) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *TokenIntrospectResponse) SetTenantId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TenantId = v
}

func (x *TokenIntrospectResponse) SetTenant(v string) {
	x.xxx_hidden_Tenant = v
}

func (x *TokenIntrospectResponse) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *TokenIntrospectResponse) SetGrant(v *Grant) {
	x.xxx_hidden_Grant = v
}

func (x *TokenIntrospectResponse) SetExpires(v *timestamppb.Timestamp) {
	x.xxx_hidden_Expires = v
}

func (x *TokenIntrospectResponse) HasGrant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Grant != nil
}

func (x *TokenIntrospectResponse) HasExpires() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expires != nil
}

func (x *TokenIntrospectResponse) ClearGrant() {
	x.xxx_hidden_Grant = nil
}

func (x *TokenIntrospectResponse) ClearExpires() {
	x.xxx_hidden_Expires = nil
}

type TokenIntrospectResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Who to serve the request as, by identifier.
	//
	// **Not necessarily the row the token hangs off.** An identity store keeps a
	// token as a row so that revoking one is a delete, and that row is the right
	// actor for the store's own trail; it is the wrong actor for the app in
	// front, whose rows are about people and which would otherwise resolve a
	// token identifier to nobody. So the store decides which of the two crosses,
	// and what crosses is the one the calling app can look up.
	Id []byte
	// The tenant the store says holds the actor.
	//
	// A claim to be disagreed with, and the interceptor does disagree: the
	// calling app's resolver reads its own row, learns which tenant really holds
	// the actor there, and the call is refused when the two differ. So a token
	// cannot move somebody between tenants by saying they moved. See
	// `auth.Identity.TenantId`.
	TenantId []byte
	// The same pair by name, for a store that keeps no identifier the calling app
	// would recognise. Exactly one of the two ways is expected.
	Tenant string
	Alias  string
	// What the token was narrowed to, which is at most what the actor allows.
	Grant *Grant
	// When the token stops working, unset for one that does not.
	//
	// It crosses because a **stream** needs it. A unary call carries its
	// credential every time and is refused at the next one; a stream reads it
	// once, at the handshake, and without this would be served for as long as it
	// stays open -- which for a Watch is until somebody hangs up.
	Expires *timestamppb.Timestamp
}

func (b0 TokenIntrospectResponse_builder) Build() *TokenIntrospectResponse {
	m0 := &TokenIntrospectResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Grant = b.Grant
	x.xxx_hidden_Expires = b.Expires
	return m0
}

// Grant is `frame.Grant` as it crosses: three axes, each either narrowed to a
// list or not narrowed at all.
//
// # Why every axis is a flag and a list
//
// Because the two answers that matter most are both an empty list. "Every
// tenant" and "no tenant whatsoever" are the same repeated field, and protobuf
// has nothing to tell them apart -- an unset repeated field and an empty one
// are one value on the wire.
//
// So the flag is written beside the list, and the flag's zero is the safe one:
// a field nobody filled in is `false`, which means narrowed, and narrowed to an
// empty list allows **nothing**. A store that forgets an axis hands out a token
// that can do nothing, which somebody notices within the minute. The other way
// round it hands out one that can do everything, which nobody notices at all.
//
// That is `frame.Grant`'s own rule -- its zero value allows nothing -- kept
// across the wire rather than restated. The mapping is in `auth`, so this
// message and that rule cannot drift apart in two places.
type Grant struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AnyTenant bool                   `protobuf:"varint,1,opt,name=any_tenant,json=anyTenant"`
	xxx_hidden_Tenants   [][]byte               `protobuf:"bytes,2,rep,name=tenants"`
	xxx_hidden_AnySet    bool                   `protobuf:"varint,3,opt,name=any_set,json=anySet"`
	xxx_hidden_Sets      [][]byte               `protobuf:"bytes,4,rep,name=sets"`
	xxx_hidden_AnyAction bool                   `protobuf:"varint,5,opt,name=any_action,json=anyAction"`
	xxx_hidden_Actions   []string               `protobuf:"bytes,6,rep,name=actions"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_payday_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_payday_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Grant) GetAnyTenant() bool {
	if x != nil {
		return x.xxx_hidden_AnyTenant
	}
	return false
}

func (x *Grant) GetTenants() [][]byte {
	if x != nil {
		return x.xxx_hidden_Tenants
	}
	return nil
}

func (x *Grant) GetAnySet() bool {
	if x != nil {
		return x.xxx_hidden_AnySet
	}
	return false
}

func (x *Grant) GetSets() [][]byte {
	if x != nil {
		return x.xxx_hidden_Sets
	}
	return nil
}

func (x *Grant) GetAnyAction() bool {
	if x != nil {
		return x.xxx_hidden_AnyAction
	}
	return false
}

func (x *Grant) GetActions() []string {
	if x != nil {
		return x.xxx_hidden_Actions
	}
	return nil
}

func (x *Grant) SetAnyTenant(v bool) {
	x.xxx_hidden_AnyTenant = v
}

func (x *Grant) SetTenants(v [][]byte) {
	x.xxx_hidden_Tenants = v
}

func (x *Grant) SetAnySet(v bool) {
	x.xxx_hidden_AnySet = v
}

func (x *Grant) SetSets(v [][]byte) {
	x.xxx_hidden_Sets = v
}

func (x *Grant) SetAnyAction(v bool) {
	x.xxx_hidden_AnyAction = v
}

func (x *Grant) SetActions(v []string) {
	x.xxx_hidden_Actions = v
}

type Grant_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether the tenants are narrowed at all; when false, `tenants` is the whole
	// of what is allowed.
	AnyTenant bool
	Tenants   [][]byte
	// The second axis, whatever the app declared at field 3 -- a site, a cell, a
	// region. An app that declared none has nothing to say here and answers
	// `any_set`.
	AnySet bool
	Sets   [][]byte
	// The methods, by the name gRpc knows them by: "/app.RobotService/Get".
	//
	// Opaque to whoever stores them. They are the **calling** app's method names,
	// which the identity store has no way to check and should not try to -- it
	// would need every app's service descriptors, and a token would stop working
	// the day an app added an RPC the store had not heard of.
	//
	// What makes that safe is that a grant only ever takes away. The calling app
	// decides what the actor may do, as it always did, and this narrows the
	// answer; a method named here that the actor cannot call is still refused.
	AnyAction bool
	Actions   []string
}

func (b0 Grant_builder) Build() *Grant {
	m0 := &Grant{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AnyTenant = b.AnyTenant
	x.xxx_hidden_Tenants = b.Tenants
	x.xxx_hidden_AnySet = b.AnySet
	x.xxx_hidden_Sets = b.Sets
	x.xxx_hidden_AnyAction = b.AnyAction
	x.xxx_hidden_Actions = b.Actions
	return m0
}

var File_payday_token_proto protoreflect.FileDescriptor

const file_payday_token_proto_rawDesc = "" +
	"\n" +
	"\x12payday/token.proto\x12\x06payday\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x16TokenIntrospectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xcf\x01\n" +
	"\x17TokenIntrospectResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\fR\btenantId\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12#\n" +
	"\x05grant\x18\x05 \x01(\v2\r.payday.GrantR\x05grant\x124\n" +
	"\aexpires\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"\xa6\x01\n" +
	"\x05Grant\x12\x1d\n" +
	"\n" +
	"any_tenant\x18\x01 \x01(\bR\tanyTenant\x12\x18\n" +
	"\atenants\x18\x02 \x03(\fR\atenants\x12\x17\n" +
	"\aany_set\x18\x03 \x01(\bR\x06anySet\x12\x12\n" +
	"\x04sets\x18\x04 \x03(\fR\x04sets\x12\x1d\n" +
	"\n" +
	"any_action\x18\x05 \x01(\bR\tanyAction\x12\x18\n" +
	"\aactions\x18\x06 \x03(\tR\aactions2]\n" +
	"\fTokenService\x12M\n" +
	"\n" +
	"Introspect\x12\x1e.payday.TokenIntrospectRequest\x1a\x1f.payday.TokenIntrospectResponseB&Z\x1fgithub.com/lesomnus/payday/pdpb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_payday_token_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payday_token_proto_goTypes = []any{
	(*TokenIntrospectRequest)(nil),  // 0: payday.TokenIntrospectRequest
	(*TokenIntrospectResponse)(nil), // 1: payday.TokenIntrospectResponse
	(*Grant)(nil),                   // 2: payday.Grant
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_payday_token_proto_depIdxs = []int32{
	2, // 0: payday.TokenIntrospectResponse.grant:type_name -> payday.Grant
	3, // 1: payday.TokenIntrospectResponse.expires:type_name -> google.protobuf.Timestamp
	0, // 2: payday.TokenService.Introspect:input_type -> payday.TokenIntrospectRequest
	1, // 3: payday.TokenService.Introspect:output_type -> payday.TokenIntrospectResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payday_token_proto_init() }
func file_payday_token_proto_init() {
	if File_payday_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payday_token_proto_rawDesc), len(file_payday_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payday_token_proto_goTypes,
		DependencyIndexes: file_payday_token_proto_depIdxs,
		MessageInfos:      file_payday_token_proto_msgTypes,
	}.Build()
	File_payday_token_proto = out.File
	file_payday_token_proto_goTypes = nil
	file_payday_token_proto_depIdxs = nil
}
