// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: app/robot_svc.proto

package apptest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotService_Add_FullMethodName   = "/app.RobotService/Add"
	RobotService_Get_FullMethodName   = "/app.RobotService/Get"
	RobotService_Patch_FullMethodName = "/app.RobotService/Patch"
	RobotService_Apply_FullMethodName = "/app.RobotService/Apply"
	RobotService_Erase_FullMethodName = "/app.RobotService/Erase"
	RobotService_List_FullMethodName  = "/app.RobotService/List"
)

// RobotServiceClient is the client API for RobotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobotServiceClient interface {
	// Add creates a new Robot
	Add(ctx context.Context, in *RobotAddRequest, opts ...grpc.CallOption) (*Robot, error)
	// Get retrieves a Robot
	Get(ctx context.Context, in *RobotGetRequest, opts ...grpc.CallOption) (*Robot, error)
	// Patch updates an existing Robot
	Patch(ctx context.Context, in *RobotPatchRequest, opts ...grpc.CallOption) (*Robot, error)
	// Apply applies a patch document to an existing Robot
	Apply(ctx context.Context, in *RobotApplyRequest, opts ...grpc.CallOption) (*Robot, error)
	// Erase deletes a Robot
	Erase(ctx context.Context, in *RobotRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List reads Robots a page at a time.
	List(ctx context.Context, in *RobotListRequest, opts ...grpc.CallOption) (*RobotListResponse, error)
}

type robotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotServiceClient(cc grpc.ClientConnInterface) RobotServiceClient {
	return &robotServiceClient{cc}
}

func (c *robotServiceClient) Add(ctx context.Context, in *RobotAddRequest, opts ...grpc.CallOption) (*Robot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Robot)
	err := c.cc.Invoke(ctx, RobotService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServiceClient) Get(ctx context.Context, in *RobotGetRequest, opts ...grpc.CallOption) (*Robot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Robot)
	err := c.cc.Invoke(ctx, RobotService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServiceClient) Patch(ctx context.Context, in *RobotPatchRequest, opts ...grpc.CallOption) (*Robot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Robot)
	err := c.cc.Invoke(ctx, RobotService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServiceClient) Apply(ctx context.Context, in *RobotApplyRequest, opts ...grpc.CallOption) (*Robot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Robot)
	err := c.cc.Invoke(ctx, RobotService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServiceClient) Erase(ctx context.Context, in *RobotRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RobotService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServiceClient) List(ctx context.Context, in *RobotListRequest, opts ...grpc.CallOption) (*RobotListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RobotListResponse)
	err := c.cc.Invoke(ctx, RobotService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotServiceServer is the server API for RobotService service.
// All implementations must embed UnimplementedRobotServiceServer
// for forward compatibility.
type RobotServiceServer interface {
	// Add creates a new Robot
	Add(context.Context, *RobotAddRequest) (*Robot, error)
	// Get retrieves a Robot
	Get(context.Context, *RobotGetRequest) (*Robot, error)
	// Patch updates an existing Robot
	Patch(context.Context, *RobotPatchRequest) (*Robot, error)
	// Apply applies a patch document to an existing Robot
	Apply(context.Context, *RobotApplyRequest) (*Robot, error)
	// Erase deletes a Robot
	Erase(context.Context, *RobotRef) (*emptypb.Empty, error)
	// List reads Robots a page at a time.
	List(context.Context, *RobotListRequest) (*RobotListResponse, error)
	mustEmbedUnimplementedRobotServiceServer()
}

// UnimplementedRobotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotServiceServer struct{}

func (UnimplementedRobotServiceServer) Add(context.Context, *RobotAddRequest) (*Robot, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedRobotServiceServer) Get(context.Context, *RobotGetRequest) (*Robot, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRobotServiceServer) Patch(context.Context, *RobotPatchRequest) (*Robot, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedRobotServiceServer) Apply(context.Context, *RobotApplyRequest) (*Robot, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedRobotServiceServer) Erase(context.Context, *RobotRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedRobotServiceServer) List(context.Context, *RobotListRequest) (*RobotListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRobotServiceServer) mustEmbedUnimplementedRobotServiceServer() {}
func (UnimplementedRobotServiceServer) testEmbeddedByValue()                      {}

// UnsafeRobotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotServiceServer will
// result in compilation errors.
type UnsafeRobotServiceServer interface {
	mustEmbedUnimplementedRobotServiceServer()
}

func RegisterRobotServiceServer(s grpc.ServiceRegistrar, srv RobotServiceServer) {
	// If the following call panics, it indicates UnimplementedRobotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotService_ServiceDesc, srv)
}

func _RobotService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).Add(ctx, req.(*RobotAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).Get(ctx, req.(*RobotGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).Patch(ctx, req.(*RobotPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).Apply(ctx, req.(*RobotApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).Erase(ctx, req.(*RobotRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).List(ctx, req.(*RobotListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RobotService_ServiceDesc is the grpc.ServiceDesc for RobotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.RobotService",
	HandlerType: (*RobotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _RobotService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RobotService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _RobotService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _RobotService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _RobotService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RobotService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/robot_svc.proto",
}

const (
	JointService_Add_FullMethodName   = "/app.JointService/Add"
	JointService_Get_FullMethodName   = "/app.JointService/Get"
	JointService_Patch_FullMethodName = "/app.JointService/Patch"
	JointService_Apply_FullMethodName = "/app.JointService/Apply"
	JointService_Erase_FullMethodName = "/app.JointService/Erase"
)

// JointServiceClient is the client API for JointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JointServiceClient interface {
	// Add creates a new Joint
	Add(ctx context.Context, in *JointAddRequest, opts ...grpc.CallOption) (*Joint, error)
	// Get retrieves a Joint
	Get(ctx context.Context, in *JointGetRequest, opts ...grpc.CallOption) (*Joint, error)
	// Patch updates an existing Joint
	Patch(ctx context.Context, in *JointPatchRequest, opts ...grpc.CallOption) (*Joint, error)
	// Apply applies a patch document to an existing Joint
	Apply(ctx context.Context, in *JointApplyRequest, opts ...grpc.CallOption) (*Joint, error)
	// Erase deletes a Joint
	Erase(ctx context.Context, in *JointRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type jointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJointServiceClient(cc grpc.ClientConnInterface) JointServiceClient {
	return &jointServiceClient{cc}
}

func (c *jointServiceClient) Add(ctx context.Context, in *JointAddRequest, opts ...grpc.CallOption) (*Joint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Joint)
	err := c.cc.Invoke(ctx, JointService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointServiceClient) Get(ctx context.Context, in *JointGetRequest, opts ...grpc.CallOption) (*Joint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Joint)
	err := c.cc.Invoke(ctx, JointService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointServiceClient) Patch(ctx context.Context, in *JointPatchRequest, opts ...grpc.CallOption) (*Joint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Joint)
	err := c.cc.Invoke(ctx, JointService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointServiceClient) Apply(ctx context.Context, in *JointApplyRequest, opts ...grpc.CallOption) (*Joint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Joint)
	err := c.cc.Invoke(ctx, JointService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointServiceClient) Erase(ctx context.Context, in *JointRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JointService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JointServiceServer is the server API for JointService service.
// All implementations must embed UnimplementedJointServiceServer
// for forward compatibility.
type JointServiceServer interface {
	// Add creates a new Joint
	Add(context.Context, *JointAddRequest) (*Joint, error)
	// Get retrieves a Joint
	Get(context.Context, *JointGetRequest) (*Joint, error)
	// Patch updates an existing Joint
	Patch(context.Context, *JointPatchRequest) (*Joint, error)
	// Apply applies a patch document to an existing Joint
	Apply(context.Context, *JointApplyRequest) (*Joint, error)
	// Erase deletes a Joint
	Erase(context.Context, *JointRef) (*emptypb.Empty, error)
	mustEmbedUnimplementedJointServiceServer()
}

// UnimplementedJointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJointServiceServer struct{}

func (UnimplementedJointServiceServer) Add(context.Context, *JointAddRequest) (*Joint, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedJointServiceServer) Get(context.Context, *JointGetRequest) (*Joint, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedJointServiceServer) Patch(context.Context, *JointPatchRequest) (*Joint, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedJointServiceServer) Apply(context.Context, *JointApplyRequest) (*Joint, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedJointServiceServer) Erase(context.Context, *JointRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedJointServiceServer) mustEmbedUnimplementedJointServiceServer() {}
func (UnimplementedJointServiceServer) testEmbeddedByValue()                      {}

// UnsafeJointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JointServiceServer will
// result in compilation errors.
type UnsafeJointServiceServer interface {
	mustEmbedUnimplementedJointServiceServer()
}

func RegisterJointServiceServer(s grpc.ServiceRegistrar, srv JointServiceServer) {
	// If the following call panics, it indicates UnimplementedJointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JointService_ServiceDesc, srv)
}

func _JointService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JointAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JointService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointServiceServer).Add(ctx, req.(*JointAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JointGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JointService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointServiceServer).Get(ctx, req.(*JointGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JointPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JointService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointServiceServer).Patch(ctx, req.(*JointPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JointApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JointService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointServiceServer).Apply(ctx, req.(*JointApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JointRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JointService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointServiceServer).Erase(ctx, req.(*JointRef))
	}
	return interceptor(ctx, in, info, handler)
}

// JointService_ServiceDesc is the grpc.ServiceDesc for JointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.JointService",
	HandlerType: (*JointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _JointService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _JointService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _JointService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _JointService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _JointService_Erase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/robot_svc.proto",
}

const (
	FleetService_Add_FullMethodName   = "/app.FleetService/Add"
	FleetService_Get_FullMethodName   = "/app.FleetService/Get"
	FleetService_Patch_FullMethodName = "/app.FleetService/Patch"
	FleetService_Apply_FullMethodName = "/app.FleetService/Apply"
	FleetService_Erase_FullMethodName = "/app.FleetService/Erase"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetServiceClient interface {
	// Add creates a new Fleet
	Add(ctx context.Context, in *FleetAddRequest, opts ...grpc.CallOption) (*Fleet, error)
	// Get retrieves a Fleet
	Get(ctx context.Context, in *FleetGetRequest, opts ...grpc.CallOption) (*Fleet, error)
	// Patch updates an existing Fleet
	Patch(ctx context.Context, in *FleetPatchRequest, opts ...grpc.CallOption) (*Fleet, error)
	// Apply applies a patch document to an existing Fleet
	Apply(ctx context.Context, in *FleetApplyRequest, opts ...grpc.CallOption) (*Fleet, error)
	// Erase deletes a Fleet
	Erase(ctx context.Context, in *FleetRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) Add(ctx context.Context, in *FleetAddRequest, opts ...grpc.CallOption) (*Fleet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fleet)
	err := c.cc.Invoke(ctx, FleetService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Get(ctx context.Context, in *FleetGetRequest, opts ...grpc.CallOption) (*Fleet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fleet)
	err := c.cc.Invoke(ctx, FleetService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Patch(ctx context.Context, in *FleetPatchRequest, opts ...grpc.CallOption) (*Fleet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fleet)
	err := c.cc.Invoke(ctx, FleetService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Apply(ctx context.Context, in *FleetApplyRequest, opts ...grpc.CallOption) (*Fleet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fleet)
	err := c.cc.Invoke(ctx, FleetService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Erase(ctx context.Context, in *FleetRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FleetService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations must embed UnimplementedFleetServiceServer
// for forward compatibility.
type FleetServiceServer interface {
	// Add creates a new Fleet
	Add(context.Context, *FleetAddRequest) (*Fleet, error)
	// Get retrieves a Fleet
	Get(context.Context, *FleetGetRequest) (*Fleet, error)
	// Patch updates an existing Fleet
	Patch(context.Context, *FleetPatchRequest) (*Fleet, error)
	// Apply applies a patch document to an existing Fleet
	Apply(context.Context, *FleetApplyRequest) (*Fleet, error)
	// Erase deletes a Fleet
	Erase(context.Context, *FleetRef) (*emptypb.Empty, error)
	mustEmbedUnimplementedFleetServiceServer()
}

// UnimplementedFleetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) Add(context.Context, *FleetAddRequest) (*Fleet, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedFleetServiceServer) Get(context.Context, *FleetGetRequest) (*Fleet, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedFleetServiceServer) Patch(context.Context, *FleetPatchRequest) (*Fleet, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedFleetServiceServer) Apply(context.Context, *FleetApplyRequest) (*Fleet, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedFleetServiceServer) Erase(context.Context, *FleetRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedFleetServiceServer) mustEmbedUnimplementedFleetServiceServer() {}
func (UnimplementedFleetServiceServer) testEmbeddedByValue()                      {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call panics, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Add(ctx, req.(*FleetAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Get(ctx, req.(*FleetGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Patch(ctx, req.(*FleetPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Apply(ctx, req.(*FleetApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Erase(ctx, req.(*FleetRef))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _FleetService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _FleetService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _FleetService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _FleetService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _FleetService_Erase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/robot_svc.proto",
}

const (
	CellService_Add_FullMethodName   = "/app.CellService/Add"
	CellService_Get_FullMethodName   = "/app.CellService/Get"
	CellService_Patch_FullMethodName = "/app.CellService/Patch"
	CellService_Apply_FullMethodName = "/app.CellService/Apply"
	CellService_Erase_FullMethodName = "/app.CellService/Erase"
)

// CellServiceClient is the client API for CellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CellServiceClient interface {
	// Add creates a new Cell
	Add(ctx context.Context, in *CellAddRequest, opts ...grpc.CallOption) (*Cell, error)
	// Get retrieves a Cell
	Get(ctx context.Context, in *CellGetRequest, opts ...grpc.CallOption) (*Cell, error)
	// Patch updates an existing Cell
	Patch(ctx context.Context, in *CellPatchRequest, opts ...grpc.CallOption) (*Cell, error)
	// Apply applies a patch document to an existing Cell
	Apply(ctx context.Context, in *CellApplyRequest, opts ...grpc.CallOption) (*Cell, error)
	// Erase deletes a Cell
	Erase(ctx context.Context, in *CellRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type cellServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCellServiceClient(cc grpc.ClientConnInterface) CellServiceClient {
	return &cellServiceClient{cc}
}

func (c *cellServiceClient) Add(ctx context.Context, in *CellAddRequest, opts ...grpc.CallOption) (*Cell, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cell)
	err := c.cc.Invoke(ctx, CellService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) Get(ctx context.Context, in *CellGetRequest, opts ...grpc.CallOption) (*Cell, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cell)
	err := c.cc.Invoke(ctx, CellService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) Patch(ctx context.Context, in *CellPatchRequest, opts ...grpc.CallOption) (*Cell, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cell)
	err := c.cc.Invoke(ctx, CellService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) Apply(ctx context.Context, in *CellApplyRequest, opts ...grpc.CallOption) (*Cell, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cell)
	err := c.cc.Invoke(ctx, CellService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) Erase(ctx context.Context, in *CellRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CellService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CellServiceServer is the server API for CellService service.
// All implementations must embed UnimplementedCellServiceServer
// for forward compatibility.
type CellServiceServer interface {
	// Add creates a new Cell
	Add(context.Context, *CellAddRequest) (*Cell, error)
	// Get retrieves a Cell
	Get(context.Context, *CellGetRequest) (*Cell, error)
	// Patch updates an existing Cell
	Patch(context.Context, *CellPatchRequest) (*Cell, error)
	// Apply applies a patch document to an existing Cell
	Apply(context.Context, *CellApplyRequest) (*Cell, error)
	// Erase deletes a Cell
	Erase(context.Context, *CellRef) (*emptypb.Empty, error)
	mustEmbedUnimplementedCellServiceServer()
}

// UnimplementedCellServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCellServiceServer struct{}

func (UnimplementedCellServiceServer) Add(context.Context, *CellAddRequest) (*Cell, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCellServiceServer) Get(context.Context, *CellGetRequest) (*Cell, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCellServiceServer) Patch(context.Context, *CellPatchRequest) (*Cell, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedCellServiceServer) Apply(context.Context, *CellApplyRequest) (*Cell, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedCellServiceServer) Erase(context.Context, *CellRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedCellServiceServer) mustEmbedUnimplementedCellServiceServer() {}
func (UnimplementedCellServiceServer) testEmbeddedByValue()                     {}

// UnsafeCellServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CellServiceServer will
// result in compilation errors.
type UnsafeCellServiceServer interface {
	mustEmbedUnimplementedCellServiceServer()
}

func RegisterCellServiceServer(s grpc.ServiceRegistrar, srv CellServiceServer) {
	// If the following call panics, it indicates UnimplementedCellServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CellService_ServiceDesc, srv)
}

func _CellService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Add(ctx, req.(*CellAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Get(ctx, req.(*CellGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Patch(ctx, req.(*CellPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Apply(ctx, req.(*CellApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Erase(ctx, req.(*CellRef))
	}
	return interceptor(ctx, in, info, handler)
}

// CellService_ServiceDesc is the grpc.ServiceDesc for CellService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CellService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.CellService",
	HandlerType: (*CellServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _CellService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CellService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _CellService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _CellService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _CellService_Erase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/robot_svc.proto",
}
