// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: app/robot.proto

package apptest

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Robot is an ordinary entity: it belongs to a tenant, and is read only by
// callers who may see that tenant.
type Robot struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Robot) Reset() {
	*x = Robot{}
	mi := &file_app_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Robot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Robot) ProtoMessage() {}

func (x *Robot) ProtoReflect() protoreflect.Message {
	mi := &file_app_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Robot) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Robot) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Robot) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Robot) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Robot) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Robot) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Robot) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Robot) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Robot) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Robot) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Robot) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *Robot) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Robot_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Tenant      *Tenant
	Alias       string
	DateCreated *timestamppb.Timestamp
}

func (b0 Robot_builder) Build() *Robot {
	m0 := &Robot{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

// Joint reaches its tenant through the Robot it is part of, which is what a
// `via` of more than one step is for. Nothing else about it is interesting.
type Joint struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id    []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Robot *Robot                 `protobuf:"bytes,2,opt,name=robot"`
	xxx_hidden_Alias string                 `protobuf:"bytes,4,opt,name=alias"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Joint) Reset() {
	*x = Joint{}
	mi := &file_app_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Joint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Joint) ProtoMessage() {}

func (x *Joint) ProtoReflect() protoreflect.Message {
	mi := &file_app_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Joint) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Joint) GetRobot() *Robot {
	if x != nil {
		return x.xxx_hidden_Robot
	}
	return nil
}

func (x *Joint) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Joint) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Joint) SetRobot(v *Robot) {
	x.xxx_hidden_Robot = v
}

func (x *Joint) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Joint) HasRobot() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Robot != nil
}

func (x *Joint) ClearRobot() {
	x.xxx_hidden_Robot = nil
}

type Joint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    []byte
	Robot *Robot
	Alias string
}

func (b0 Joint_builder) Build() *Joint {
	m0 := &Joint{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Robot = b.Robot
	x.xxx_hidden_Alias = b.Alias
	return m0
}

// Fleet is shared by the whole deployment, and says so. A reader of the schema
// can tell that from "somebody forgot" because there is no way to forget.
type Fleet struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id    []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Alias string                 `protobuf:"bytes,4,opt,name=alias"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Fleet) Reset() {
	*x = Fleet{}
	mi := &file_app_robot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fleet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fleet) ProtoMessage() {}

func (x *Fleet) ProtoReflect() protoreflect.Message {
	mi := &file_app_robot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Fleet) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Fleet) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Fleet) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Fleet) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

type Fleet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    []byte
	Alias string
}

func (b0 Fleet_builder) Build() *Fleet {
	m0 := &Fleet{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Alias = b.Alias
	return m0
}

// Cell was added to answer one question: what does adding an entity cost?
// Nothing below this line is Go, and nothing else in this app was touched.
type Cell struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id     []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias  string                 `protobuf:"bytes,4,opt,name=alias"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_app_robot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_app_robot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Cell) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Cell) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Cell) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Cell) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Cell) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Cell) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Cell) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Cell) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

type Cell_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     []byte
	Tenant *Tenant
	Alias  string
}

func (b0 Cell_builder) Build() *Cell {
	m0 := &Cell{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	return m0
}

var File_app_robot_proto protoreflect.FileDescriptor

const file_app_robot_proto_rawDesc = "" +
	"\n" +
	"\x0fapp/robot.proto\x12\x03app\x1a\x13payday/tenant.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\xbd\x02\n" +
	"\x05Robot\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12.\n" +
	"\x06tenant\x18\x02 \x01(\v2\x0e.payday.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:\x86\x01\xca\xfc\x15G\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a\x1f\x12\x04slug\x1a\t\n" +
	"\x05alias\x10\x04\x1a\n" +
	"\n" +
	"\x06tenant\x10\x020\x01\x8a\xbb\x167\b\a2'\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x04\n" +
	"\x02id\x12\x06tenant\x1a\x03ref 2(d:\x00\"\b\n" +
	"\x06tenant\"\x84\x01\n" +
	"\x05Joint\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12(\n" +
	"\x05robot\x18\x02 \x01(\v2\n" +
	".app.RobotB\x06\xf2\x82\x16\x02@\x01R\x05robot\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias:\x1e\xca\xfc\x15\x04\x12\x02\x10\x01\x8a\xbb\x16\x12\b\b\"\x0e\n" +
	"\frobot.tenant\"T\n" +
	"\x05Fleet\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12\x1c\n" +
	"\x05alias\x18\x04 \x01(\tB\x06\xea\x82\x16\x020\x01R\x05alias:\x10\xca\xfc\x15\x04\x12\x02\x10\x01\x8a\xbb\x16\x04\b\t*\x00\"\x83\x01\n" +
	"\x04Cell\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12.\n" +
	"\x06tenant\x18\x02 \x01(\v2\x0e.payday.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias:\x18\xca\xfc\x15\x04\x12\x02\x10\x01\x8a\xbb\x16\f\b\n" +
	"\"\b\n" +
	"\x06tenantB2Z+github.com/lesomnus/payday/internal/apptest\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_robot_proto_goTypes = []any{
	(*Robot)(nil),                 // 0: app.Robot
	(*Joint)(nil),                 // 1: app.Joint
	(*Fleet)(nil),                 // 2: app.Fleet
	(*Cell)(nil),                  // 3: app.Cell
	(*Tenant)(nil),                // 4: payday.Tenant
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_app_robot_proto_depIdxs = []int32{
	4, // 0: app.Robot.tenant:type_name -> payday.Tenant
	5, // 1: app.Robot.date_created:type_name -> google.protobuf.Timestamp
	0, // 2: app.Joint.robot:type_name -> app.Robot
	4, // 3: app.Cell.tenant:type_name -> payday.Tenant
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_robot_proto_init() }
func file_app_robot_proto_init() {
	if File_app_robot_proto != nil {
		return
	}
	file_payday_tenant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_robot_proto_rawDesc), len(file_app_robot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_robot_proto_goTypes,
		DependencyIndexes: file_app_robot_proto_depIdxs,
		MessageInfos:      file_app_robot_proto_msgTypes,
	}.Build()
	File_app_robot_proto = out.File
	file_app_robot_proto_goTypes = nil
	file_app_robot_proto_depIdxs = nil
}
