// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package apptest

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *CellRef) Pick() *CellGetRequest {
	return CellGetRequest_builder{Ref: x}.Build()
}

func (x *Cell) Ref() *CellRef {
	if v := x.GetId(); len(v) > 0 {
		return CellById(v)
	}

	return nil
}

func (x *Cell) Pick() *CellGetRequest {
	return x.Ref().Pick()
}

func (x *CellRef) Picks(v *Cell) bool {
	switch x.WhichKey() {
	case CellRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *CellGetRequest) WithSelect(f func(s *CellSelect)) *CellGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&CellSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Cell) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Cell) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func CellById(v []byte) *CellRef {
	x := &CellRef{}
	x.SetId(v)
	return x
}

func CellGetById(v []byte) *CellGetRequest {
	return CellGetRequest_builder{Ref: CellById(v)}.Build()
}

func (x *RobotRef) Pick() *RobotGetRequest {
	return RobotGetRequest_builder{Ref: x}.Build()
}

func (x *Robot) Ref() *RobotRef {
	if v := x.GetId(); len(v) > 0 {
		return RobotById(v)
	}
	{
		v1 := x.GetAlias()
		v2 := x.GetTenant()
		if len(v1) > 0 && v2 != nil {
			return RobotBySlug(v1, v2.Ref())
		}
	}

	return nil
}

func (x *Robot) Pick() *RobotGetRequest {
	return x.Ref().Pick()
}

func (x *RobotRef) Picks(v *Robot) bool {
	switch x.WhichKey() {
	case RobotRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case RobotRef_Slug_case:
		x := x.GetSlug()
		return (x.GetAlias() == v.GetAlias()) &&
			(x.GetTenant().Picks(v.GetTenant()))
	default:
		return false
	}
}

func (x *RobotGetRequest) WithSelect(f func(s *RobotSelect)) *RobotGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&RobotSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Robot) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Robot) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func RobotById(v []byte) *RobotRef {
	x := &RobotRef{}
	x.SetId(v)
	return x
}

func RobotGetById(v []byte) *RobotGetRequest {
	return RobotGetRequest_builder{Ref: RobotById(v)}.Build()
}

func RobotBySlug(alias string, tenant *TenantRef) *RobotRef {
	x := &RobotRefBySlug{}
	x.SetAlias(alias)
	x.SetTenant(tenant)
	return RobotRef_builder{Slug: x}.Build()
}

func RobotGetBySlug(alias string, tenant *TenantRef) *RobotGetRequest {
	return RobotGetRequest_builder{Ref: RobotBySlug(alias, tenant)}.Build()
}

func (x *JointRef) Pick() *JointGetRequest {
	return JointGetRequest_builder{Ref: x}.Build()
}

func (x *Joint) Ref() *JointRef {
	if v := x.GetId(); len(v) > 0 {
		return JointById(v)
	}

	return nil
}

func (x *Joint) Pick() *JointGetRequest {
	return x.Ref().Pick()
}

func (x *JointRef) Picks(v *Joint) bool {
	switch x.WhichKey() {
	case JointRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *JointGetRequest) WithSelect(f func(s *JointSelect)) *JointGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&JointSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Joint) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Joint) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func JointById(v []byte) *JointRef {
	x := &JointRef{}
	x.SetId(v)
	return x
}

func JointGetById(v []byte) *JointGetRequest {
	return JointGetRequest_builder{Ref: JointById(v)}.Build()
}

func (x *FleetRef) Pick() *FleetGetRequest {
	return FleetGetRequest_builder{Ref: x}.Build()
}

func (x *Fleet) Ref() *FleetRef {
	if v := x.GetId(); len(v) > 0 {
		return FleetById(v)
	}
	if v := x.GetAlias(); len(v) > 0 {
		return FleetByAlias(v)
	}

	return nil
}

func (x *Fleet) Pick() *FleetGetRequest {
	return x.Ref().Pick()
}

func (x *FleetRef) Picks(v *Fleet) bool {
	switch x.WhichKey() {
	case FleetRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case FleetRef_Alias_case:
		return x.GetAlias() == v.GetAlias()
	default:
		return false
	}
}

func (x *FleetGetRequest) WithSelect(f func(s *FleetSelect)) *FleetGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&FleetSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Fleet) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Fleet) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func FleetById(v []byte) *FleetRef {
	x := &FleetRef{}
	x.SetId(v)
	return x
}

func FleetByAlias(v string) *FleetRef {
	x := &FleetRef{}
	x.SetAlias(v)
	return x
}

func FleetGetById(v []byte) *FleetGetRequest {
	return FleetGetRequest_builder{Ref: FleetById(v)}.Build()
}

func FleetGetByAlias(v string) *FleetGetRequest {
	return FleetGetRequest_builder{Ref: FleetByAlias(v)}.Build()
}

func (x *ReadingRef) Pick() *ReadingGetRequest {
	return ReadingGetRequest_builder{Ref: x}.Build()
}

func (x *Reading) Ref() *ReadingRef {
	if v := x.GetId(); len(v) > 0 {
		return ReadingById(v)
	}

	return nil
}

func (x *Reading) Pick() *ReadingGetRequest {
	return x.Ref().Pick()
}

func (x *ReadingRef) Picks(v *Reading) bool {
	switch x.WhichKey() {
	case ReadingRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *ReadingGetRequest) WithSelect(f func(s *ReadingSelect)) *ReadingGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ReadingSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Reading) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Reading) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func ReadingById(v []byte) *ReadingRef {
	x := &ReadingRef{}
	x.SetId(v)
	return x
}

func ReadingGetById(v []byte) *ReadingGetRequest {
	return ReadingGetRequest_builder{Ref: ReadingById(v)}.Build()
}
