// Code generated by protoc-gen-orm-service. DO NOT EDIT.
// source: shared/thing.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shared/thing_svc.g.proto

package apptest

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThingAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ThingAddRequest) Reset() {
	*x = ThingAddRequest{}
	mi := &file_shared_thing_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingAddRequest) ProtoMessage() {}

func (x *ThingAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_thing_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ThingAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *ThingAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *ThingAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ThingAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *ThingAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ThingAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type ThingAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    []byte
	Alias string
}

func (b0 ThingAddRequest_builder) Build() *ThingAddRequest {
	m0 := &ThingAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Alias = b.Alias
	return m0
}

type ThingRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isThingRef_Key         `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThingRef) Reset() {
	*x = ThingRef{}
	mi := &file_shared_thing_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingRef) ProtoMessage() {}

func (x *ThingRef) ProtoReflect() protoreflect.Message {
	mi := &file_shared_thing_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ThingRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*thingRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *ThingRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &thingRef_Id{v}
}

func (x *ThingRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *ThingRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*thingRef_Id)
	return ok
}

func (x *ThingRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *ThingRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*thingRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

const ThingRef_Key_not_set_case case_ThingRef_Key = 0
const ThingRef_Id_case case_ThingRef_Key = 1

func (x *ThingRef) WhichKey() case_ThingRef_Key {
	if x == nil {
		return ThingRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *thingRef_Id:
		return ThingRef_Id_case
	default:
		return ThingRef_Key_not_set_case
	}
}

type ThingRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id []byte
	// -- end of xxx_hidden_Key
}

func (b0 ThingRef_builder) Build() *ThingRef {
	m0 := &ThingRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &thingRef_Id{b.Id}
	}
	return m0
}

type case_ThingRef_Key protoreflect.FieldNumber

func (x case_ThingRef_Key) String() string {
	md := file_shared_thing_svc_g_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isThingRef_Key interface {
	isThingRef_Key()
}

type thingRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

func (*thingRef_Id) isThingRef_Key() {}

type ThingSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_DateErased  bool                   `protobuf:"varint,14,opt,name=date_erased,json=dateErased"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ThingSelect) Reset() {
	*x = ThingSelect{}
	mi := &file_shared_thing_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingSelect) ProtoMessage() {}

func (x *ThingSelect) ProtoReflect() protoreflect.Message {
	mi := &file_shared_thing_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ThingSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *ThingSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *ThingSelect) GetDateErased() bool {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return false
}

func (x *ThingSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ThingSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ThingSelect) SetDateErased(v bool) {
	x.xxx_hidden_DateErased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ThingSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ThingSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ThingSelect) HasDateErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ThingSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *ThingSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = false
}

func (x *ThingSelect) ClearDateErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_DateErased = false
}

type ThingSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All        *bool
	Alias      *bool
	DateErased *bool
}

func (b0 ThingSelect_builder) Build() *ThingSelect {
	m0 := &ThingSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_All = *b.All
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.DateErased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_DateErased = *b.DateErased
	}
	return m0
}

type ThingGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *ThingRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *ThingSelect           `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThingGetRequest) Reset() {
	*x = ThingGetRequest{}
	mi := &file_shared_thing_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingGetRequest) ProtoMessage() {}

func (x *ThingGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_thing_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ThingGetRequest) GetRef() *ThingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ThingGetRequest) GetSelect() *ThingSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *ThingGetRequest) SetRef(v *ThingRef) {
	x.xxx_hidden_Ref = v
}

func (x *ThingGetRequest) SetSelect(v *ThingSelect) {
	x.xxx_hidden_Select = v
}

func (x *ThingGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ThingGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *ThingGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ThingGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type ThingGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *ThingRef
	Select *ThingSelect
}

func (b0 ThingGetRequest_builder) Build() *ThingGetRequest {
	m0 := &ThingGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type ThingPatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *ThingRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,8,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ThingPatchRequest) Reset() {
	*x = ThingPatchRequest{}
	mi := &file_shared_thing_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingPatchRequest) ProtoMessage() {}

func (x *ThingPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_thing_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ThingPatchRequest) GetRef() *ThingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ThingPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *ThingPatchRequest) SetRef(v *ThingRef) {
	x.xxx_hidden_Ref = v
}

func (x *ThingPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ThingPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ThingPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ThingPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ThingPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

type ThingPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *ThingRef
	Alias *string
}

func (b0 ThingPatchRequest_builder) Build() *ThingPatchRequest {
	m0 := &ThingPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type ThingApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *ThingRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ThingApplyRequest) Reset() {
	*x = ThingApplyRequest{}
	mi := &file_shared_thing_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingApplyRequest) ProtoMessage() {}

func (x *ThingApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_thing_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ThingApplyRequest) GetRef() *ThingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ThingApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *ThingApplyRequest) SetRef(v *ThingRef) {
	x.xxx_hidden_Ref = v
}

func (x *ThingApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *ThingApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ThingApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *ThingApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ThingApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type ThingApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *ThingRef
	Patch *patchpb.Patch
}

func (b0 ThingApplyRequest_builder) Build() *ThingApplyRequest {
	m0 := &ThingApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

var File_shared_thing_svc_g_proto protoreflect.FileDescriptor

const file_shared_thing_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x18shared/thing_svc.g.proto\x12\x06shared\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11patch/patch.proto\x1a\x12shared/thing.proto\">\n" +
	"\x0fThingAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1b\n" +
	"\x05alias\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\"#\n" +
	"\bThingRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02idB\x05\n" +
	"\x03key\"V\n" +
	"\vThingSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x1f\n" +
	"\vdate_erased\x18\x0e \x01(\bR\n" +
	"dateErased\"b\n" +
	"\x0fThingGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shared.ThingRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.shared.ThingSelectR\x06select\"M\n" +
	"\x11ThingPatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shared.ThingRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\b \x01(\tR\x05alias\"[\n" +
	"\x11ThingApplyRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shared.ThingRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch2\x85\x02\n" +
	"\fThingService\x12-\n" +
	"\x03Add\x12\x17.shared.ThingAddRequest\x1a\r.shared.Thing\x12-\n" +
	"\x03Get\x12\x17.shared.ThingGetRequest\x1a\r.shared.Thing\x121\n" +
	"\x05Patch\x12\x19.shared.ThingPatchRequest\x1a\r.shared.Thing\x121\n" +
	"\x05Apply\x12\x19.shared.ThingApplyRequest\x1a\r.shared.Thing\x121\n" +
	"\x05Erase\x12\x10.shared.ThingRef\x1a\x16.google.protobuf.EmptyB-Z+github.com/lesomnus/payday/internal/apptestb\beditionsp\xe8\a"

var file_shared_thing_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_thing_svc_g_proto_goTypes = []any{
	(*ThingAddRequest)(nil),   // 0: shared.ThingAddRequest
	(*ThingRef)(nil),          // 1: shared.ThingRef
	(*ThingSelect)(nil),       // 2: shared.ThingSelect
	(*ThingGetRequest)(nil),   // 3: shared.ThingGetRequest
	(*ThingPatchRequest)(nil), // 4: shared.ThingPatchRequest
	(*ThingApplyRequest)(nil), // 5: shared.ThingApplyRequest
	(*patchpb.Patch)(nil),     // 6: patch.Patch
	(*Thing)(nil),             // 7: shared.Thing
	(*emptypb.Empty)(nil),     // 8: google.protobuf.Empty
}
var file_shared_thing_svc_g_proto_depIdxs = []int32{
	1,  // 0: shared.ThingGetRequest.ref:type_name -> shared.ThingRef
	2,  // 1: shared.ThingGetRequest.select:type_name -> shared.ThingSelect
	1,  // 2: shared.ThingPatchRequest.ref:type_name -> shared.ThingRef
	1,  // 3: shared.ThingApplyRequest.ref:type_name -> shared.ThingRef
	6,  // 4: shared.ThingApplyRequest.patch:type_name -> patch.Patch
	0,  // 5: shared.ThingService.Add:input_type -> shared.ThingAddRequest
	3,  // 6: shared.ThingService.Get:input_type -> shared.ThingGetRequest
	4,  // 7: shared.ThingService.Patch:input_type -> shared.ThingPatchRequest
	5,  // 8: shared.ThingService.Apply:input_type -> shared.ThingApplyRequest
	1,  // 9: shared.ThingService.Erase:input_type -> shared.ThingRef
	7,  // 10: shared.ThingService.Add:output_type -> shared.Thing
	7,  // 11: shared.ThingService.Get:output_type -> shared.Thing
	7,  // 12: shared.ThingService.Patch:output_type -> shared.Thing
	7,  // 13: shared.ThingService.Apply:output_type -> shared.Thing
	8,  // 14: shared.ThingService.Erase:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_shared_thing_svc_g_proto_init() }
func file_shared_thing_svc_g_proto_init() {
	if File_shared_thing_svc_g_proto != nil {
		return
	}
	file_shared_thing_proto_init()
	file_shared_thing_svc_g_proto_msgTypes[1].OneofWrappers = []any{
		(*thingRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_thing_svc_g_proto_rawDesc), len(file_shared_thing_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_thing_svc_g_proto_goTypes,
		DependencyIndexes: file_shared_thing_svc_g_proto_depIdxs,
		MessageInfos:      file_shared_thing_svc_g_proto_msgTypes,
	}.Build()
	File_shared_thing_svc_g_proto = out.File
	file_shared_thing_svc_g_proto_goTypes = nil
	file_shared_thing_svc_g_proto_depIdxs = nil
}
