// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package apptest

import (
	bytes "bytes"
)

func (x *ThingRef) Pick() *ThingGetRequest {
	return ThingGetRequest_builder{Ref: x}.Build()
}

func (x *Thing) Ref() *ThingRef {
	if v := x.GetId(); len(v) > 0 {
		return ThingById(v)
	}

	return nil
}

func (x *Thing) Pick() *ThingGetRequest {
	return x.Ref().Pick()
}

func (x *ThingRef) Picks(v *Thing) bool {
	switch x.WhichKey() {
	case ThingRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *ThingGetRequest) WithSelect(f func(s *ThingSelect)) *ThingGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ThingSelect{})
	}
	f(x.GetSelect())
	return x
}

func ThingById(v []byte) *ThingRef {
	x := &ThingRef{}
	x.SetId(v)
	return x
}

func ThingGetById(v []byte) *ThingGetRequest {
	return ThingGetRequest_builder{Ref: ThingById(v)}.Build()
}
