// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditColumns holds the columns for the "audit" table.
	AuditColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID},
		{Name: "trace_id", Type: field.TypeBytes},
		{Name: "action", Type: field.TypeString},
		{Name: "object_id", Type: field.TypeUUID},
		{Name: "patch", Type: field.TypeBytes},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
	}
	// AuditTable holds the schema information for the "audit" table.
	AuditTable = &schema.Table{
		Name:       "audit",
		Columns:    AuditColumns,
		PrimaryKey: []*schema.Column{AuditColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "audit_object_id",
				Unique:  false,
				Columns: []*schema.Column{AuditColumns[5]},
			},
			{
				Name:    "audit_tenant_id_date_created",
				Unique:  false,
				Columns: []*schema.Column{AuditColumns[1], AuditColumns[7]},
			},
		},
	}
	// CellColumns holds the columns for the "cell" table.
	CellColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString},
		{Name: "cell_tenant", Type: field.TypeUUID},
	}
	// CellTable holds the schema information for the "cell" table.
	CellTable = &schema.Table{
		Name:       "cell",
		Columns:    CellColumns,
		PrimaryKey: []*schema.Column{CellColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cell_tenant_tenant",
				Columns:    []*schema.Column{CellColumns[2]},
				RefColumns: []*schema.Column{TenantColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// FleetColumns holds the columns for the "fleet" table.
	FleetColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString, Unique: true},
	}
	// FleetTable holds the schema information for the "fleet" table.
	FleetTable = &schema.Table{
		Name:       "fleet",
		Columns:    FleetColumns,
		PrimaryKey: []*schema.Column{FleetColumns[0]},
	}
	// HolderColumns holds the columns for the "holder" table.
	HolderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "date_updated", Type: field.TypeTime},
		{Name: "date_erased", Type: field.TypeTime, Nullable: true},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
		{Name: "idp_subject", Type: field.TypeString},
		{Name: "holder_tenant", Type: field.TypeUUID},
	}
	// HolderTable holds the schema information for the "holder" table.
	HolderTable = &schema.Table{
		Name:       "holder",
		Columns:    HolderColumns,
		PrimaryKey: []*schema.Column{HolderColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "holder_tenant_tenant",
				Columns:    []*schema.Column{HolderColumns[9]},
				RefColumns: []*schema.Column{TenantColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "holder_alias_holder_tenant",
				Unique:  true,
				Columns: []*schema.Column{HolderColumns[1], HolderColumns[9]},
				Annotation: &entsql.IndexAnnotation{
					Where: "date_erased IS NULL",
				},
			},
		},
	}
	// JointColumns holds the columns for the "joint" table.
	JointColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString},
		{Name: "joint_robot", Type: field.TypeUUID},
	}
	// JointTable holds the schema information for the "joint" table.
	JointTable = &schema.Table{
		Name:       "joint",
		Columns:    JointColumns,
		PrimaryKey: []*schema.Column{JointColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "joint_robot_robot",
				Columns:    []*schema.Column{JointColumns[2]},
				RefColumns: []*schema.Column{RobotColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// OutboxColumns holds the columns for the "outbox" table.
	OutboxColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID},
		{Name: "method", Type: field.TypeString},
		{Name: "by", Type: field.TypeString},
		{Name: "object_id", Type: field.TypeUUID},
		{Name: "patch", Type: field.TypeBytes},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
	}
	// OutboxTable holds the schema information for the "outbox" table.
	OutboxTable = &schema.Table{
		Name:       "outbox",
		Columns:    OutboxColumns,
		PrimaryKey: []*schema.Column{OutboxColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "outbox_id",
				Unique:  false,
				Columns: []*schema.Column{OutboxColumns[0]},
			},
		},
	}
	// RobotColumns holds the columns for the "robot" table.
	RobotColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString},
		{Name: "date_updated", Type: field.TypeTime},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
		{Name: "robot_tenant", Type: field.TypeUUID},
	}
	// RobotTable holds the schema information for the "robot" table.
	RobotTable = &schema.Table{
		Name:       "robot",
		Columns:    RobotColumns,
		PrimaryKey: []*schema.Column{RobotColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "robot_tenant_tenant",
				Columns:    []*schema.Column{RobotColumns[4]},
				RefColumns: []*schema.Column{TenantColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "robot_date_created_id",
				Unique:  false,
				Columns: []*schema.Column{RobotColumns[3], RobotColumns[0]},
			},
			{
				Name:    "robot_alias_robot_tenant",
				Unique:  true,
				Columns: []*schema.Column{RobotColumns[1], RobotColumns[4]},
			},
		},
	}
	// TenantColumns holds the columns for the "tenant" table.
	TenantColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "date_updated", Type: field.TypeTime},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
	}
	// TenantTable holds the schema information for the "tenant" table.
	TenantTable = &schema.Table{
		Name:       "tenant",
		Columns:    TenantColumns,
		PrimaryKey: []*schema.Column{TenantColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditTable,
		CellTable,
		FleetTable,
		HolderTable,
		JointTable,
		OutboxTable,
		RobotTable,
		TenantTable,
	}
)

func init() {
	AuditTable.Annotation = &entsql.Annotation{
		Table: "audit",
	}
	CellTable.ForeignKeys[0].RefTable = TenantTable
	CellTable.Annotation = &entsql.Annotation{
		Table: "cell",
	}
	FleetTable.Annotation = &entsql.Annotation{
		Table: "fleet",
	}
	HolderTable.ForeignKeys[0].RefTable = TenantTable
	HolderTable.Annotation = &entsql.Annotation{
		Table: "holder",
	}
	JointTable.ForeignKeys[0].RefTable = RobotTable
	JointTable.Annotation = &entsql.Annotation{
		Table: "joint",
	}
	OutboxTable.Annotation = &entsql.Annotation{
		Table: "outbox",
	}
	RobotTable.ForeignKeys[0].RefTable = TenantTable
	RobotTable.Annotation = &entsql.Annotation{
		Table: "robot",
	}
	TenantTable.Annotation = &entsql.Annotation{
		Table: "tenant",
	}
}
