// Code generated by ent, DO NOT EDIT.

package fleet

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the fleet type in the database.
	Label = "fleet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// Table holds the table name of the fleet in the database.
	Table = "fleet"
)

// Columns holds all SQL columns for fleet fields.
var Columns = []string{
	FieldID,
	FieldAlias,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Fleet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}
