// Code generated by ent, DO NOT EDIT.

package robot

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the robot type in the database.
	Label = "robot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldSecret holds the string denoting the secret field in the database.
	FieldSecret = "secret"
	// FieldDateAttested holds the string denoting the date_attested field in the database.
	FieldDateAttested = "date_attested"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldDateErased holds the string denoting the date_erased field in the database.
	FieldDateErased = "date_erased"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldThingID holds the string denoting the thing_id field in the database.
	FieldThingID = "thing_id"
	// FieldCellID holds the string denoting the cell_id field in the database.
	FieldCellID = "cell_id"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeThing holds the string denoting the thing edge name in mutations.
	EdgeThing = "thing"
	// EdgeCell holds the string denoting the cell edge name in mutations.
	EdgeCell = "cell"
	// Table holds the table name of the robot in the database.
	Table = "robot"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "robot"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenant"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// ThingTable is the table that holds the thing relation/edge.
	ThingTable = "robot"
	// ThingInverseTable is the table name for the Thing entity.
	// It exists in this package in order to avoid circular dependency with the "thing" package.
	ThingInverseTable = "thing"
	// ThingColumn is the table column denoting the thing relation/edge.
	ThingColumn = "thing_id"
	// CellTable is the table that holds the cell relation/edge.
	CellTable = "robot"
	// CellInverseTable is the table name for the Cell entity.
	// It exists in this package in order to avoid circular dependency with the "cell" package.
	CellInverseTable = "cell"
	// CellColumn is the table column denoting the cell relation/edge.
	CellColumn = "cell_id"
)

// Columns holds all SQL columns for robot fields.
var Columns = []string{
	FieldID,
	FieldAlias,
	FieldSecret,
	FieldDateAttested,
	FieldDateUpdated,
	FieldDateCreated,
	FieldDateErased,
	FieldTenantID,
	FieldThingID,
	FieldCellID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Robot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}

// ByDateAttested orders the results by the date_attested field.
func ByDateAttested(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateAttested, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByDateErased orders the results by the date_erased field.
func ByDateErased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateErased, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByThingID orders the results by the thing_id field.
func ByThingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThingID, opts...).ToFunc()
}

// ByCellID orders the results by the cell_id field.
func ByCellID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCellID, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByThingField orders the results by thing field.
func ByThingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newThingStep(), sql.OrderByField(field, opts...))
	}
}

// ByCellField orders the results by cell field.
func ByCellField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCellStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
	)
}
func newThingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ThingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ThingTable, ThingColumn),
	)
}
func newCellStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CellInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CellTable, CellColumn),
	)
}
