// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/tenant.proto

package schema

import (
	ent "entgo.io/ent"
	entsql "entgo.io/ent/dialect/entsql"
	schema "entgo.io/ent/schema"
	field "entgo.io/ent/schema/field"
	uuid "github.com/google/uuid"
)

type Tenant struct {
	ent.Schema
}

func (Tenant) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Unique().
			Immutable(),
		field.String("alias").
			Unique(),
		field.Time("date_created").
			Immutable().
			Optional(),
	}
}

func (Tenant) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "tenant"},
	}
}
