// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/fleet"
)

// Fleet is the model entity for the Fleet schema.
type Fleet struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias        string `json:"alias,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Fleet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fleet.FieldAlias:
			values[i] = new(sql.NullString)
		case fleet.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Fleet fields.
func (_m *Fleet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fleet.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case fleet.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Fleet.
// This includes values selected through modifiers, order, etc.
func (_m *Fleet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Fleet.
// Note that you need to call Fleet.Unwrap() before calling this method if this Fleet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Fleet) Update() *FleetUpdateOne {
	return NewFleetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Fleet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Fleet) Unwrap() *Fleet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Fleet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Fleet) String() string {
	var builder strings.Builder
	builder.WriteString("Fleet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("alias=")
	builder.WriteString(_m.Alias)
	builder.WriteByte(')')
	return builder.String()
}

// Fleets is a parsable slice of Fleet.
type Fleets []*Fleet
