// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/lesomnus/payday/internal/apptest/internal/ent/fleet"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// FleetDelete is the builder for deleting a Fleet entity.
type FleetDelete struct {
	config
	hooks    []Hook
	mutation *FleetMutation
}

// Where appends a list predicates to the FleetDelete builder.
func (_d *FleetDelete) Where(ps ...predicate.Fleet) *FleetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FleetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FleetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FleetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fleet.Table, sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeUUID))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FleetDeleteOne is the builder for deleting a single Fleet entity.
type FleetDeleteOne struct {
	_d *FleetDelete
}

// Where appends a list predicates to the FleetDelete builder.
func (_d *FleetDeleteOne) Where(ps ...predicate.Fleet) *FleetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FleetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fleet.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FleetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
