// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/payday/outbox.proto

package ent

import (
	apptest "github.com/lesomnus/payday/internal/apptest"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Outbox) Proto() *apptest.Outbox {
	x := &apptest.Outbox{}
	x.SetId(e.Id[:])
	x.SetTenantId(e.TenantId[:])
	x.SetActorId(e.ActorId[:])
	x.SetMethod(e.Method)
	x.SetBy(e.By)
	x.SetObjectId(e.ObjectId[:])
	x.SetPatch(e.Patch)
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
