// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/payday/internal/apptest/internal/ent/pairing"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/robot"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// PairingCreate is the builder for creating a Pairing entity.
type PairingCreate struct {
	config
	mutation *PairingMutation
	hooks    []Hook
}

// SetDateCreated sets the "date_created" field.
func (_c *PairingCreate) SetDateCreated(v time.Time) *PairingCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *PairingCreate) SetNillableDateCreated(v *time.Time) *PairingCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetLeadId sets the "lead_id" field.
func (_c *PairingCreate) SetLeadId(v uuid.UUID) *PairingCreate {
	_c.mutation.SetLeadId(v)
	return _c
}

// SetFollowId sets the "follow_id" field.
func (_c *PairingCreate) SetFollowId(v uuid.UUID) *PairingCreate {
	_c.mutation.SetFollowId(v)
	return _c
}

// SetId sets the "id" field.
func (_c *PairingCreate) SetId(v uuid.UUID) *PairingCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetLead sets the "lead" edge to the Robot entity.
func (_c *PairingCreate) SetLead(v *Robot) *PairingCreate {
	return _c.SetLeadId(v.Id)
}

// SetFollow sets the "follow" edge to the Robot entity.
func (_c *PairingCreate) SetFollow(v *Robot) *PairingCreate {
	return _c.SetFollowId(v.Id)
}

// Mutation returns the PairingMutation object of the builder.
func (_c *PairingCreate) Mutation() *PairingMutation {
	return _c.mutation
}

// Save creates the Pairing in the database.
func (_c *PairingCreate) Save(ctx context.Context) (*Pairing, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PairingCreate) SaveX(ctx context.Context) *Pairing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PairingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PairingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PairingCreate) check() error {
	if _, ok := _c.mutation.LeadId(); !ok {
		return &ValidationError{Name: "lead_id", err: errors.New(`ent: missing required field "Pairing.lead_id"`)}
	}
	if _, ok := _c.mutation.FollowId(); !ok {
		return &ValidationError{Name: "follow_id", err: errors.New(`ent: missing required field "Pairing.follow_id"`)}
	}
	if len(_c.mutation.LeadIds()) == 0 {
		return &ValidationError{Name: "lead", err: errors.New(`ent: missing required edge "Pairing.lead"`)}
	}
	if len(_c.mutation.FollowIds()) == 0 {
		return &ValidationError{Name: "follow", err: errors.New(`ent: missing required edge "Pairing.follow"`)}
	}
	return nil
}

func (_c *PairingCreate) sqlSave(ctx context.Context) (*Pairing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		sv, ok := _spec.Id.Value.(field.ValueScanner)
		if !ok {
			sv = pairing.ValueScanner.Id.ScanValue()
			if err := sv.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
		}
		if value, err := pairing.ValueScanner.Id.FromValue(sv); err != nil {
			return nil, err
		} else {
			_node.Id = value
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *PairingCreate) createSpec() (*Pairing, *sqlgraph.CreateSpec, error) {
	var (
		_node = &Pairing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pairing.Table, sqlgraph.NewFieldSpec(pairing.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		vv, err := pairing.ValueScanner.Id.Value(id)
		if err != nil {
			return nil, nil, err
		}
		_spec.Id.Value = vv
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(pairing.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.LeadIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pairing.LeadTable,
			Columns: []string{pairing.LeadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(robot.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			vv, err := robot.ValueScanner.Id.Value(k)
			if err != nil {
				return nil, nil, err
			}
			edge.Target.Nodes = append(edge.Target.Nodes, vv)
		}
		_node.LeadId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FollowIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pairing.FollowTable,
			Columns: []string{pairing.FollowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(robot.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			vv, err := robot.ValueScanner.Id.Value(k)
			if err != nil {
				return nil, nil, err
			}
			edge.Target.Nodes = append(edge.Target.Nodes, vv)
		}
		_node.FollowId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec, nil
}

// PairingCreateBulk is the builder for creating many Pairing entities in bulk.
type PairingCreateBulk struct {
	config
	err      error
	builders []*PairingCreate
}

// Save creates the Pairing entities in the database.
func (_c *PairingCreateBulk) Save(ctx context.Context) ([]*Pairing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pairing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PairingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i], err = builder.createSpec()
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				if specs[i].Id.Value != nil {
					sv, ok := specs[i].Id.Value.(field.ValueScanner)
					if !ok {
						sv = pairing.ValueScanner.Id.ScanValue()
						if err := sv.Scan(specs[i].Id.Value); err != nil {
							return nil, err
						}
					}
					if id, err := pairing.ValueScanner.Id.FromValue(sv); err != nil {
						return nil, err
					} else {
						nodes[i].Id = id
					}
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PairingCreateBulk) SaveX(ctx context.Context) []*Pairing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PairingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PairingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
