// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/pairing"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/robot"
)

// Pairing is the model entity for the Pairing schema.
type Pairing struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// LeadID holds the value of the "lead_id" field.
	LeadID uuid.UUID `json:"lead_id,omitempty"`
	// FollowID holds the value of the "follow_id" field.
	FollowID uuid.UUID `json:"follow_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PairingQuery when eager-loading is set.
	Edges        PairingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PairingEdges holds the relations/edges for other nodes in the graph.
type PairingEdges struct {
	// Lead holds the value of the lead edge.
	Lead *Robot `json:"lead,omitempty"`
	// Follow holds the value of the follow edge.
	Follow *Robot `json:"follow,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LeadOrErr returns the Lead value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PairingEdges) LeadOrErr() (*Robot, error) {
	if e.Lead != nil {
		return e.Lead, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: robot.Label}
	}
	return nil, &NotLoadedError{edge: "lead"}
}

// FollowOrErr returns the Follow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PairingEdges) FollowOrErr() (*Robot, error) {
	if e.Follow != nil {
		return e.Follow, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: robot.Label}
	}
	return nil, &NotLoadedError{edge: "follow"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pairing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pairing.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case pairing.FieldID, pairing.FieldLeadID, pairing.FieldFollowID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pairing fields.
func (_m *Pairing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pairing.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pairing.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case pairing.FieldLeadID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field lead_id", values[i])
			} else if value != nil {
				_m.LeadID = *value
			}
		case pairing.FieldFollowID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field follow_id", values[i])
			} else if value != nil {
				_m.FollowID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pairing.
// This includes values selected through modifiers, order, etc.
func (_m *Pairing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLead queries the "lead" edge of the Pairing entity.
func (_m *Pairing) QueryLead() *RobotQuery {
	return NewPairingClient(_m.config).QueryLead(_m)
}

// QueryFollow queries the "follow" edge of the Pairing entity.
func (_m *Pairing) QueryFollow() *RobotQuery {
	return NewPairingClient(_m.config).QueryFollow(_m)
}

// Update returns a builder for updating this Pairing.
// Note that you need to call Pairing.Unwrap() before calling this method if this Pairing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Pairing) Update() *PairingUpdateOne {
	return NewPairingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Pairing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Pairing) Unwrap() *Pairing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pairing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Pairing) String() string {
	var builder strings.Builder
	builder.WriteString("Pairing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("lead_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeadID))
	builder.WriteString(", ")
	builder.WriteString("follow_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FollowID))
	builder.WriteByte(')')
	return builder.String()
}

// Pairings is a parsable slice of Pairing.
type Pairings []*Pairing
