// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"uuid"

	"github.com/lesomnus/payday/internal/apptest/internal/ent/pairing"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/predicate"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/robot"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// PairingQuery is the builder for querying Pairing entities.
type PairingQuery struct {
	config
	ctx        *QueryContext
	order      []pairing.OrderOption
	inters     []Interceptor
	predicates []predicate.Pairing
	withLead   *RobotQuery
	withFollow *RobotQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PairingQuery builder.
func (_q *PairingQuery) Where(ps ...predicate.Pairing) *PairingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PairingQuery) Limit(limit int) *PairingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PairingQuery) Offset(offset int) *PairingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PairingQuery) Unique(unique bool) *PairingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PairingQuery) Order(o ...pairing.OrderOption) *PairingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLead chains the current query on the "lead" edge.
func (_q *PairingQuery) QueryLead() *RobotQuery {
	query := (&RobotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pairing.Table, pairing.FieldId, selector),
			sqlgraph.To(robot.Table, robot.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, pairing.LeadTable, pairing.LeadColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFollow chains the current query on the "follow" edge.
func (_q *PairingQuery) QueryFollow() *RobotQuery {
	query := (&RobotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pairing.Table, pairing.FieldId, selector),
			sqlgraph.To(robot.Table, robot.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, pairing.FollowTable, pairing.FollowColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Pairing entity from the query.
// Returns a *NotFoundError when no Pairing was found.
func (_q *PairingQuery) First(ctx context.Context) (*Pairing, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pairing.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PairingQuery) FirstX(ctx context.Context) *Pairing {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstId returns the first Pairing Id from the query.
// Returns a *NotFoundError when no Pairing Id was found.
func (_q *PairingQuery) FirstId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryFirstId)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pairing.Label}
		return
	}
	return ids[0], nil
}

// FirstIdX is like FirstId, but panics if an error occurs.
func (_q *PairingQuery) FirstIdX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstId(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Pairing entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Pairing entity is found.
// Returns a *NotFoundError when no Pairing entities are found.
func (_q *PairingQuery) Only(ctx context.Context) (*Pairing, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pairing.Label}
	default:
		return nil, &NotSingularError{pairing.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PairingQuery) OnlyX(ctx context.Context) *Pairing {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyId is like Only, but returns the only Pairing Id in the query.
// Returns a *NotSingularError when more than one Pairing Id is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PairingQuery) OnlyId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyId)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pairing.Label}
	default:
		err = &NotSingularError{pairing.Label}
	}
	return
}

// OnlyIdX is like OnlyId, but panics if an error occurs.
func (_q *PairingQuery) OnlyIdX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyId(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Pairing entities.
func (_q *PairingQuery) All(ctx context.Context) ([]*Pairing, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Pairing, *PairingQuery]()
	return withInterceptors[[]*Pairing](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PairingQuery) AllX(ctx context.Context) []*Pairing {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Ids executes the query and returns a list of Pairing Ids.
func (_q *PairingQuery) Ids(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIds)
	var nodes []*Pairing
	if nodes, err = _q.Select(pairing.FieldId).All(ctx); err != nil {
		return nil, err
	}
	ids = make([]uuid.UUID, len(nodes))
	for i := range nodes {
		ids[i] = nodes[i].Id
	}
	return ids, nil
}

// IdsX is like Ids, but panics if an error occurs.
func (_q *PairingQuery) IdsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.Ids(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PairingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PairingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PairingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PairingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstId(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PairingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PairingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PairingQuery) Clone() *PairingQuery {
	if _q == nil {
		return nil
	}
	return &PairingQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]pairing.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Pairing{}, _q.predicates...),
		withLead:   _q.withLead.Clone(),
		withFollow: _q.withFollow.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithLead tells the query-builder to eager-load the nodes that are connected to
// the "lead" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PairingQuery) WithLead(opts ...func(*RobotQuery)) *PairingQuery {
	query := (&RobotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLead = query
	return _q
}

// WithFollow tells the query-builder to eager-load the nodes that are connected to
// the "follow" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PairingQuery) WithFollow(opts ...func(*RobotQuery)) *PairingQuery {
	query := (&RobotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFollow = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DateCreated time.Time `json:"date_created,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Pairing.Query().
//		GroupBy(pairing.FieldDateCreated).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PairingQuery) GroupBy(field string, fields ...string) *PairingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PairingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pairing.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DateCreated time.Time `json:"date_created,omitempty"`
//	}
//
//	client.Pairing.Query().
//		Select(pairing.FieldDateCreated).
//		Scan(ctx, &v)
func (_q *PairingQuery) Select(fields ...string) *PairingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PairingSelect{PairingQuery: _q}
	sbuild.label = pairing.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PairingSelect configured with the given aggregations.
func (_q *PairingQuery) Aggregate(fns ...AggregateFunc) *PairingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PairingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pairing.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PairingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Pairing, error) {
	var (
		nodes       = []*Pairing{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withLead != nil,
			_q.withFollow != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Pairing).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Pairing{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLead; query != nil {
		if err := _q.loadLead(ctx, query, nodes, nil,
			func(n *Pairing, e *Robot) { n.Edges.Lead = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFollow; query != nil {
		if err := _q.loadFollow(ctx, query, nodes, nil,
			func(n *Pairing, e *Robot) { n.Edges.Follow = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PairingQuery) loadLead(ctx context.Context, query *RobotQuery, nodes []*Pairing, init func(*Pairing), assign func(*Pairing, *Robot)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Pairing)
	for i := range nodes {
		fk := nodes[i].LeadId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(robot.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "lead_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PairingQuery) loadFollow(ctx context.Context, query *RobotQuery, nodes []*Pairing, init func(*Pairing), assign func(*Pairing, *Robot)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Pairing)
	for i := range nodes {
		fk := nodes[i].FollowId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(robot.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "follow_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PairingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PairingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pairing.Table, pairing.Columns, sqlgraph.NewFieldSpec(pairing.FieldId, field.TypeUuid))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pairing.FieldId)
		for i := range fields {
			if fields[i] != pairing.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withLead != nil {
			_spec.Node.AddColumnOnce(pairing.FieldLeadId)
		}
		if _q.withFollow != nil {
			_spec.Node.AddColumnOnce(pairing.FieldFollowId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PairingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pairing.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pairing.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *PairingQuery) Modify(modifiers ...func(s *sql.Selector)) *PairingSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// PairingGroupBy is the group-by builder for Pairing entities.
type PairingGroupBy struct {
	selector
	build *PairingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PairingGroupBy) Aggregate(fns ...AggregateFunc) *PairingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PairingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PairingQuery, *PairingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PairingGroupBy) sqlScan(ctx context.Context, root *PairingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PairingSelect is the builder for selecting fields of Pairing entities.
type PairingSelect struct {
	*PairingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PairingSelect) Aggregate(fns ...AggregateFunc) *PairingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PairingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PairingQuery, *PairingSelect](ctx, _s.PairingQuery, _s, _s.inters, v)
}

func (_s *PairingSelect) sqlScan(ctx context.Context, root *PairingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *PairingSelect) Modify(modifiers ...func(s *sql.Selector)) *PairingSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
