// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/payday/internal/apptest/internal/ent/reading"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/robot"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Reading is the model entity for the Reading schema.
type Reading struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// TenantId holds the value of the "tenant_id" field.
	TenantId uuid.UUID `json:"tenant_id,omitempty"`
	// Celsius holds the value of the "celsius" field.
	Celsius float64 `json:"celsius,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// RobotId holds the value of the "robot_id" field.
	RobotId uuid.UUID `json:"robot_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReadingQuery when eager-loading is set.
	Edges        ReadingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReadingEdges holds the relations/edges for other nodes in the graph.
type ReadingEdges struct {
	// Robot holds the value of the robot edge.
	Robot *Robot `json:"robot,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RobotOrErr returns the Robot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReadingEdges) RobotOrErr() (*Robot, error) {
	if e.Robot != nil {
		return e.Robot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: robot.Label}
	}
	return nil, &NotLoadedError{edge: "robot"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Reading) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reading.FieldId:
			values[i] = reading.ValueScanner.Id.ScanValue()
		case reading.FieldCelsius:
			values[i] = new(sql.NullFloat64)
		case reading.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case reading.FieldTenantId:
			values[i] = reading.ValueScanner.TenantId.ScanValue()
		case reading.FieldRobotId:
			values[i] = reading.ValueScanner.RobotId.ScanValue()
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Reading fields.
func (_m *Reading) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reading.FieldId:
			if value, err := reading.ValueScanner.Id.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.Id = value
			}
		case reading.FieldTenantId:
			if value, err := reading.ValueScanner.TenantId.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.TenantId = value
			}
		case reading.FieldCelsius:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field celsius", values[i])
			} else if value.Valid {
				_m.Celsius = value.Float64
			}
		case reading.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case reading.FieldRobotId:
			if value, err := reading.ValueScanner.RobotId.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.RobotId = value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Reading.
// This includes values selected through modifiers, order, etc.
func (_m *Reading) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRobot queries the "robot" edge of the Reading entity.
func (_m *Reading) QueryRobot() *RobotQuery {
	return NewReadingClient(_m.config).QueryRobot(_m)
}

// Update returns a builder for updating this Reading.
// Note that you need to call Reading.Unwrap() before calling this method if this Reading
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Reading) Update() *ReadingUpdateOne {
	return NewReadingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Reading entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Reading) Unwrap() *Reading {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Reading is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Reading) String() string {
	var builder strings.Builder
	builder.WriteString("Reading(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantId))
	builder.WriteString(", ")
	builder.WriteString("celsius=")
	builder.WriteString(fmt.Sprintf("%v", _m.Celsius))
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("robot_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RobotId))
	builder.WriteByte(')')
	return builder.String()
}

// ReadingList is a parsable slice of Reading.
type ReadingList []*Reading
