// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/payday/internal/apptest/internal/ent/cell"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/predicate"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/robot"
	"github.com/lesomnus/payday/internal/apptest/internal/ent/thing"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// RobotUpdate is the builder for updating Robot entities.
type RobotUpdate struct {
	config
	hooks     []Hook
	mutation  *RobotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RobotUpdate builder.
func (_u *RobotUpdate) Where(ps ...predicate.Robot) *RobotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *RobotUpdate) SetAlias(v string) *RobotUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableAlias(v *string) *RobotUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetSecret sets the "secret" field.
func (_u *RobotUpdate) SetSecret(v []byte) *RobotUpdate {
	_u.mutation.SetSecret(v)
	return _u
}

// ClearSecret clears the value of the "secret" field.
func (_u *RobotUpdate) ClearSecret() *RobotUpdate {
	_u.mutation.ClearSecret()
	return _u
}

// SetDateAttested sets the "date_attested" field.
func (_u *RobotUpdate) SetDateAttested(v time.Time) *RobotUpdate {
	_u.mutation.SetDateAttested(v)
	return _u
}

// SetNillableDateAttested sets the "date_attested" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableDateAttested(v *time.Time) *RobotUpdate {
	if v != nil {
		_u.SetDateAttested(*v)
	}
	return _u
}

// ClearDateAttested clears the value of the "date_attested" field.
func (_u *RobotUpdate) ClearDateAttested() *RobotUpdate {
	_u.mutation.ClearDateAttested()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *RobotUpdate) SetDateUpdated(v time.Time) *RobotUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableDateUpdated(v *time.Time) *RobotUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *RobotUpdate) SetDateErased(v time.Time) *RobotUpdate {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableDateErased(v *time.Time) *RobotUpdate {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *RobotUpdate) ClearDateErased() *RobotUpdate {
	_u.mutation.ClearDateErased()
	return _u
}

// SetThingId sets the "thing_id" field.
func (_u *RobotUpdate) SetThingId(v uuid.UUID) *RobotUpdate {
	_u.mutation.SetThingId(v)
	return _u
}

// SetNillableThingId sets the "thing_id" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableThingId(v *uuid.UUID) *RobotUpdate {
	if v != nil {
		_u.SetThingId(*v)
	}
	return _u
}

// ClearThingId clears the value of the "thing_id" field.
func (_u *RobotUpdate) ClearThingId() *RobotUpdate {
	_u.mutation.ClearThingId()
	return _u
}

// SetCellId sets the "cell_id" field.
func (_u *RobotUpdate) SetCellId(v uuid.UUID) *RobotUpdate {
	_u.mutation.SetCellId(v)
	return _u
}

// SetNillableCellId sets the "cell_id" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableCellId(v *uuid.UUID) *RobotUpdate {
	if v != nil {
		_u.SetCellId(*v)
	}
	return _u
}

// ClearCellId clears the value of the "cell_id" field.
func (_u *RobotUpdate) ClearCellId() *RobotUpdate {
	_u.mutation.ClearCellId()
	return _u
}

// SetThing sets the "thing" edge to the Thing entity.
func (_u *RobotUpdate) SetThing(v *Thing) *RobotUpdate {
	return _u.SetThingId(v.Id)
}

// SetCell sets the "cell" edge to the Cell entity.
func (_u *RobotUpdate) SetCell(v *Cell) *RobotUpdate {
	return _u.SetCellId(v.Id)
}

// Mutation returns the RobotMutation object of the builder.
func (_u *RobotUpdate) Mutation() *RobotMutation {
	return _u.mutation
}

// ClearThing clears the "thing" edge to the Thing entity.
func (_u *RobotUpdate) ClearThing() *RobotUpdate {
	_u.mutation.ClearThing()
	return _u
}

// ClearCell clears the "cell" edge to the Cell entity.
func (_u *RobotUpdate) ClearCell() *RobotUpdate {
	_u.mutation.ClearCell()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RobotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RobotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RobotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RobotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RobotUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Robot.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RobotUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RobotUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RobotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(robot.Table, robot.Columns, sqlgraph.NewFieldSpec(robot.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(robot.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(robot.FieldSecret, field.TypeBytes, value)
	}
	if _u.mutation.SecretCleared() {
		_spec.ClearField(robot.FieldSecret, field.TypeBytes)
	}
	if value, ok := _u.mutation.DateAttested(); ok {
		_spec.SetField(robot.FieldDateAttested, field.TypeTime, value)
	}
	if _u.mutation.DateAttestedCleared() {
		_spec.ClearField(robot.FieldDateAttested, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(robot.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(robot.FieldDateCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(robot.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(robot.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.ThingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   robot.ThingTable,
			Columns: []string{robot.ThingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(thing.FieldId, field.TypeUuid),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThingIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   robot.ThingTable,
			Columns: []string{robot.ThingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(thing.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CellCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   robot.CellTable,
			Columns: []string{robot.CellColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(cell.FieldId, field.TypeUuid),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CellIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   robot.CellTable,
			Columns: []string{robot.CellColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(cell.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{robot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RobotUpdateOne is the builder for updating a single Robot entity.
type RobotUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RobotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAlias sets the "alias" field.
func (_u *RobotUpdateOne) SetAlias(v string) *RobotUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableAlias(v *string) *RobotUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetSecret sets the "secret" field.
func (_u *RobotUpdateOne) SetSecret(v []byte) *RobotUpdateOne {
	_u.mutation.SetSecret(v)
	return _u
}

// ClearSecret clears the value of the "secret" field.
func (_u *RobotUpdateOne) ClearSecret() *RobotUpdateOne {
	_u.mutation.ClearSecret()
	return _u
}

// SetDateAttested sets the "date_attested" field.
func (_u *RobotUpdateOne) SetDateAttested(v time.Time) *RobotUpdateOne {
	_u.mutation.SetDateAttested(v)
	return _u
}

// SetNillableDateAttested sets the "date_attested" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableDateAttested(v *time.Time) *RobotUpdateOne {
	if v != nil {
		_u.SetDateAttested(*v)
	}
	return _u
}

// ClearDateAttested clears the value of the "date_attested" field.
func (_u *RobotUpdateOne) ClearDateAttested() *RobotUpdateOne {
	_u.mutation.ClearDateAttested()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *RobotUpdateOne) SetDateUpdated(v time.Time) *RobotUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableDateUpdated(v *time.Time) *RobotUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *RobotUpdateOne) SetDateErased(v time.Time) *RobotUpdateOne {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableDateErased(v *time.Time) *RobotUpdateOne {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *RobotUpdateOne) ClearDateErased() *RobotUpdateOne {
	_u.mutation.ClearDateErased()
	return _u
}

// SetThingId sets the "thing_id" field.
func (_u *RobotUpdateOne) SetThingId(v uuid.UUID) *RobotUpdateOne {
	_u.mutation.SetThingId(v)
	return _u
}

// SetNillableThingId sets the "thing_id" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableThingId(v *uuid.UUID) *RobotUpdateOne {
	if v != nil {
		_u.SetThingId(*v)
	}
	return _u
}

// ClearThingId clears the value of the "thing_id" field.
func (_u *RobotUpdateOne) ClearThingId() *RobotUpdateOne {
	_u.mutation.ClearThingId()
	return _u
}

// SetCellId sets the "cell_id" field.
func (_u *RobotUpdateOne) SetCellId(v uuid.UUID) *RobotUpdateOne {
	_u.mutation.SetCellId(v)
	return _u
}

// SetNillableCellId sets the "cell_id" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableCellId(v *uuid.UUID) *RobotUpdateOne {
	if v != nil {
		_u.SetCellId(*v)
	}
	return _u
}

// ClearCellId clears the value of the "cell_id" field.
func (_u *RobotUpdateOne) ClearCellId() *RobotUpdateOne {
	_u.mutation.ClearCellId()
	return _u
}

// SetThing sets the "thing" edge to the Thing entity.
func (_u *RobotUpdateOne) SetThing(v *Thing) *RobotUpdateOne {
	return _u.SetThingId(v.Id)
}

// SetCell sets the "cell" edge to the Cell entity.
func (_u *RobotUpdateOne) SetCell(v *Cell) *RobotUpdateOne {
	return _u.SetCellId(v.Id)
}

// Mutation returns the RobotMutation object of the builder.
func (_u *RobotUpdateOne) Mutation() *RobotMutation {
	return _u.mutation
}

// ClearThing clears the "thing" edge to the Thing entity.
func (_u *RobotUpdateOne) ClearThing() *RobotUpdateOne {
	_u.mutation.ClearThing()
	return _u
}

// ClearCell clears the "cell" edge to the Cell entity.
func (_u *RobotUpdateOne) ClearCell() *RobotUpdateOne {
	_u.mutation.ClearCell()
	return _u
}

// Where appends a list predicates to the RobotUpdate builder.
func (_u *RobotUpdateOne) Where(ps ...predicate.Robot) *RobotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RobotUpdateOne) Select(field string, fields ...string) *RobotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Robot entity.
func (_u *RobotUpdateOne) Save(ctx context.Context) (*Robot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RobotUpdateOne) SaveX(ctx context.Context) *Robot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RobotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RobotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RobotUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Robot.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RobotUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RobotUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RobotUpdateOne) sqlSave(ctx context.Context) (_node *Robot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(robot.Table, robot.Columns, sqlgraph.NewFieldSpec(robot.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Robot.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, robot.FieldId)
		for _, f := range fields {
			if !robot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != robot.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(robot.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(robot.FieldSecret, field.TypeBytes, value)
	}
	if _u.mutation.SecretCleared() {
		_spec.ClearField(robot.FieldSecret, field.TypeBytes)
	}
	if value, ok := _u.mutation.DateAttested(); ok {
		_spec.SetField(robot.FieldDateAttested, field.TypeTime, value)
	}
	if _u.mutation.DateAttestedCleared() {
		_spec.ClearField(robot.FieldDateAttested, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(robot.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(robot.FieldDateCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(robot.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(robot.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.ThingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   robot.ThingTable,
			Columns: []string{robot.ThingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(thing.FieldId, field.TypeUuid),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThingIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   robot.ThingTable,
			Columns: []string{robot.ThingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(thing.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CellCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   robot.CellTable,
			Columns: []string{robot.CellColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(cell.FieldId, field.TypeUuid),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CellIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   robot.CellTable,
			Columns: []string{robot.CellColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(cell.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Robot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{robot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
