// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/robot.proto

package ent

import (
	uuid "github.com/google/uuid"
	apptest "github.com/lesomnus/payday/internal/apptest"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Robot) Proto() *apptest.Robot {
	x := &apptest.Robot{}
	x.SetId(e.ID[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	} else if v := e.TenantID; v != *new(uuid.UUID) {
		r := &apptest.Tenant{}
		r.SetId(v[:])
		x.SetTenant(r)
	}
	x.SetAlias(e.Alias)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
func (e *Joint) Proto() *apptest.Joint {
	x := &apptest.Joint{}
	x.SetId(e.ID[:])
	if v := e.Edges.Robot; v != nil {
		x.SetRobot(v.Proto())
	} else if v := e.RobotID; v != *new(uuid.UUID) {
		r := &apptest.Robot{}
		r.SetId(v[:])
		x.SetRobot(r)
	}
	x.SetAlias(e.Alias)
	return x
}
func (e *Fleet) Proto() *apptest.Fleet {
	x := &apptest.Fleet{}
	x.SetId(e.ID[:])
	x.SetAlias(e.Alias)
	return x
}
func (e *Cell) Proto() *apptest.Cell {
	x := &apptest.Cell{}
	x.SetId(e.ID[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	} else if v := e.TenantID; v != *new(uuid.UUID) {
		r := &apptest.Tenant{}
		r.SetId(v[:])
		x.SetTenant(r)
	}
	x.SetAlias(e.Alias)
	return x
}
func (e *Reading) Proto() *apptest.Reading {
	x := &apptest.Reading{}
	x.SetId(e.ID[:])
	if v := e.Edges.Robot; v != nil {
		x.SetRobot(v.Proto())
	} else if v := e.RobotID; v != *new(uuid.UUID) {
		r := &apptest.Robot{}
		r.SetId(v[:])
		x.SetRobot(r)
	}
	x.SetCelsius(e.Celsius)
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
