// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/robot.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "errors"
	uuid "github.com/google/uuid"
	apptest "github.com/lesomnus/payday/internal/apptest"
	ent "github.com/lesomnus/payday/internal/apptest/internal/ent"
	cell "github.com/lesomnus/payday/internal/apptest/internal/ent/cell"
	fleet "github.com/lesomnus/payday/internal/apptest/internal/ent/fleet"
	joint "github.com/lesomnus/payday/internal/apptest/internal/ent/joint"
	pairing "github.com/lesomnus/payday/internal/apptest/internal/ent/pairing"
	predicate "github.com/lesomnus/payday/internal/apptest/internal/ent/predicate"
	reading "github.com/lesomnus/payday/internal/apptest/internal/ent/reading"
	robot "github.com/lesomnus/payday/internal/apptest/internal/ent/robot"
	thing "github.com/lesomnus/payday/internal/apptest/internal/ent/thing"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	graph "github.com/protobuf-orm/protobuf-orm/graph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

type CellServiceServer struct {
	Store

	apptest.UnimplementedCellServiceServer
}

// NewCellServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewCellServiceServer(db *ent.Client, opts ...Option) apptest.CellServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return CellServiceServer{Store: s.Store}
}

// CellNarrow answers with `p` and everything else that narrows a
// read of a Cell: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func CellNarrow(ctx context.Context, scope Scope, p predicate.Cell) (predicate.Cell, error) {
	ps := make([]predicate.Cell, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, cell.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.CellScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return cell.And(ps...), nil
	}
}

// narrow is [CellNarrow] with this server's own scope.
func (s CellServiceServer) narrow(ctx context.Context, p predicate.Cell) (predicate.Cell, error) {
	return CellNarrow(ctx, s.Scope, p)
}

func (s CellServiceServer) Add(ctx context.Context, req *apptest.CellAddRequest) (*apptest.Cell, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *apptest.Cell), 0, 1)
	q := st.Db.Cell.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Cell", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantID(k)
		ds = append(ds, func(v *apptest.Cell) {
			v.SetTenant(apptest.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetAlias(req.GetAlias())

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Cell already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Cell: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.CellService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s CellServiceServer) Get(ctx context.Context, req *apptest.CellGetRequest) (*apptest.Cell, error) {
	p, err := CellPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Cell.Query().Where(p)
	CellSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Cell not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectCellKey(q *ent.CellQuery) {
	q.Select(cell.FieldID)
}

func CellSelectedFields(m *apptest.CellSelect) []string {
	if m.GetAll() {
		return cell.Columns
	}

	vs := make([]string, 0, len(cell.Columns))
	{
		vs = append(vs, cell.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, cell.FieldAlias)
	}
	if m.GetDateErased() {
		vs = append(vs, cell.FieldDateErased)
	}

	return vs
}

func CellSelect(q *ent.CellQuery, m *apptest.CellSelect) {
	if !m.GetAll() {
		fields := CellSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
}

func CellSelectInit(q *ent.CellQuery, m *apptest.CellSelect) {
	if m != nil {
		CellSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
	}
}

func (s CellServiceServer) Patch(ctx context.Context, req *apptest.CellPatchRequest) (*apptest.Cell, error) {
	doc, err := ormpatch.FromPatchRequest(cellOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.CellService_Patch_FullMethodName)
}

func CellGetKey(ctx context.Context, db *ent.Client, ref *apptest.CellRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := CellPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Cell.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Cell not found")
		}
		return z, err
	}

	return v, nil
}

var cellOrmEntity = ormpatch.MustEntityOf(apptest.File_app_robot_proto, "Cell")

var cellPatchColumns = entpatch.Columns{
	1: cell.FieldID, 2: cell.TenantColumn, 4: cell.FieldAlias, 14: cell.FieldDateErased}

func (s CellServiceServer) Apply(ctx context.Context, req *apptest.CellApplyRequest) (*apptest.Cell, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.CellService_Apply_FullMethodName)
}

func (s CellServiceServer) apply(ctx context.Context, ref *apptest.CellRef, doc *patchpb.Patch, by string) (*apptest.Cell, error) {
	plan := &ormpatch.Plan{Entity: cellOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(cellOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, cellPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := CellGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.CellRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, cell.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Cell.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Cell(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Cell.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Cell not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Cell.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Cell(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Cell already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Cell: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Cell.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Cell not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s CellServiceServer) Erase(ctx context.Context, req *apptest.CellRef) (*apptest.CellEraseResponse, error) {
	p, err := CellPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Cell.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.CellEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = cell.And(p, cell.IDEQ(v))
	}

	u := st.Db.Cell.Update().Where(p)
	u.SetDateErased(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.CellService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.CellEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// CellPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Cell is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasCellWith`, where no narrowing of a Cell
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func CellPick(req *apptest.CellRef) (predicate.Cell, error) {
	p, err := pickCell(req)
	if err != nil {
		return nil, err
	}

	return cell.And(cell.DateErasedIsNil(), p), nil
}

func pickCell(req *apptest.CellRef) (predicate.Cell, error) {
	switch req.WhichKey() {
	case apptest.CellRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return cell.IDEQ(v), nil
		}
	case apptest.CellRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Cell")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type RobotServiceServer struct {
	Store

	apptest.UnimplementedRobotServiceServer
}

// NewRobotServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewRobotServiceServer(db *ent.Client, opts ...Option) apptest.RobotServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return RobotServiceServer{Store: s.Store}
}

// RobotNarrow answers with `p` and everything else that narrows a
// read of a Robot: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func RobotNarrow(ctx context.Context, scope Scope, p predicate.Robot) (predicate.Robot, error) {
	ps := make([]predicate.Robot, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, robot.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.RobotScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return robot.And(ps...), nil
	}
}

// narrow is [RobotNarrow] with this server's own scope.
func (s RobotServiceServer) narrow(ctx context.Context, p predicate.Robot) (predicate.Robot, error) {
	return RobotNarrow(ctx, s.Scope, p)
}

func (s RobotServiceServer) Add(ctx context.Context, req *apptest.RobotAddRequest) (*apptest.Robot, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *apptest.Robot), 0, 3)
	q := st.Db.Robot.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Robot", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantID(k)
		ds = append(ds, func(v *apptest.Robot) {
			v.SetTenant(apptest.Tenant_builder{Id: k[:]}.Build())
		})
	}
	if req.HasThing() {
		if k, err := ThingGetKey(ctx, st.Db, req.GetThing()); err != nil {
			return nil, err
		} else {
			q.SetThingID(k)
			ds = append(ds, func(v *apptest.Robot) {
				v.SetThing(apptest.Thing_builder{Id: k[:]}.Build())
			})
		}
	}
	if req.HasCell() {
		if k, err := CellGetKey(ctx, st.Db, req.GetCell()); err != nil {
			return nil, err
		} else {
			q.SetCellID(k)
			ds = append(ds, func(v *apptest.Robot) {
				v.SetCell(apptest.Cell_builder{Id: k[:]}.Build())
			})
		}
	}
	q.SetAlias(req.GetAlias())
	if req.HasSecret() {
		q.SetSecret(req.GetSecret())
	} else {
		q.SetSecret([]byte{})
	}
	if req.HasDateAttested() {
		q.SetDateAttested(req.GetDateAttested().AsTime())
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Robot already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Robot: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.RobotService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s RobotServiceServer) Get(ctx context.Context, req *apptest.RobotGetRequest) (*apptest.Robot, error) {
	p, err := RobotPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Robot.Query().Where(p)
	RobotSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Robot not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectRobotKey(q *ent.RobotQuery) {
	q.Select(robot.FieldID)
}

func RobotSelectedFields(m *apptest.RobotSelect) []string {
	if m.GetAll() {
		return robot.Columns
	}

	vs := make([]string, 0, len(robot.Columns))
	{
		vs = append(vs, robot.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, robot.FieldAlias)
	}
	if m.GetSecret() {
		vs = append(vs, robot.FieldSecret)
	}
	if m.GetDateAttested() {
		vs = append(vs, robot.FieldDateAttested)
	}
	if m.GetDateUpdated() {
		vs = append(vs, robot.FieldDateUpdated)
	}
	if m.GetDateCreated() {
		vs = append(vs, robot.FieldDateCreated)
	}
	if m.GetDateErased() {
		vs = append(vs, robot.FieldDateErased)
	}

	return vs
}

func RobotSelect(q *ent.RobotQuery, m *apptest.RobotSelect) {
	if !m.GetAll() {
		fields := RobotSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
	if m.HasThing() {
		q.WithThing(func(q *ent.ThingQuery) {
			q.Where(thing.DateErasedIsNil())
			ThingSelect(q, m.GetThing())
		})
	}
	if m.HasCell() {
		q.WithCell(func(q *ent.CellQuery) {
			q.Where(cell.DateErasedIsNil())
			CellSelect(q, m.GetCell())
		})
	}
}

func RobotSelectInit(q *ent.RobotQuery, m *apptest.RobotSelect) {
	if m != nil {
		RobotSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
		q.WithThing(selectThingKey)
		q.WithCell(selectCellKey)
	}
}

func (s RobotServiceServer) Patch(ctx context.Context, req *apptest.RobotPatchRequest) (*apptest.Robot, error) {
	doc, err := ormpatch.FromPatchRequest(robotOrmEntity, req.ProtoReflect(), func(ed graph.Edge, ref protoreflect.Message) (protoreflect.Value, error) {
		switch ed.Number() {
		case 30:
			k, err := ThingGetKey(ctx, s.Db, ref.Interface().(*apptest.ThingRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		case 3:
			k, err := CellGetKey(ctx, s.Db, ref.Interface().(*apptest.CellRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		}
		return protoreflect.Value{}, status.Errorf(codes.Internal, "no key resolver for edge: %s", ed.Name())
	})
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.RobotService_Patch_FullMethodName)
}

func RobotGetKey(ctx context.Context, db *ent.Client, ref *apptest.RobotRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := RobotPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Robot.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Robot not found")
		}
		return z, err
	}

	return v, nil
}

var robotOrmEntity = ormpatch.MustEntityOf(apptest.File_app_robot_proto, "Robot")

var robotPatchColumns = entpatch.Columns{
	1: robot.FieldID, 2: robot.TenantColumn, 30: robot.ThingColumn, 3: robot.CellColumn, 4: robot.FieldAlias, 8: robot.FieldSecret, 31: robot.FieldDateAttested, 13: robot.FieldDateUpdated, 15: robot.FieldDateCreated, 14: robot.FieldDateErased}

func (s RobotServiceServer) Apply(ctx context.Context, req *apptest.RobotApplyRequest) (*apptest.Robot, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.RobotService_Apply_FullMethodName)
}

func (s RobotServiceServer) apply(ctx context.Context, ref *apptest.RobotRef, doc *patchpb.Patch, by string) (*apptest.Robot, error) {
	plan := &ormpatch.Plan{Entity: robotOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(robotOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, robotPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := RobotGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.RobotRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, robot.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Robot.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Robot(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Robot.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Robot not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Robot.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Robot(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Robot already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Robot: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Robot.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Robot not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s RobotServiceServer) Erase(ctx context.Context, req *apptest.RobotRef) (*apptest.RobotEraseResponse, error) {
	p, err := RobotPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Robot.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.RobotEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = robot.And(p, robot.IDEQ(v))
	}

	u := st.Db.Robot.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.RobotService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.RobotEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// RobotPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Robot is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasRobotWith`, where no narrowing of a Robot
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func RobotPick(req *apptest.RobotRef) (predicate.Robot, error) {
	p, err := pickRobot(req)
	if err != nil {
		return nil, err
	}

	return robot.And(robot.DateErasedIsNil(), p), nil
}

func pickRobot(req *apptest.RobotRef) (predicate.Robot, error) {
	switch req.WhichKey() {
	case apptest.RobotRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return robot.IDEQ(v), nil
		}
	case apptest.RobotRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.Robot, 0, 2)
		ps = append(ps, robot.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, robot.HasTenantWith(p))
		}
		return robot.And(ps...), nil
	case apptest.RobotRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Robot")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type PairingServiceServer struct {
	Store

	apptest.UnimplementedPairingServiceServer
}

// NewPairingServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewPairingServiceServer(db *ent.Client, opts ...Option) apptest.PairingServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return PairingServiceServer{Store: s.Store}
}

// PairingNarrow answers with `p` and everything else that narrows a
// read of a Pairing, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func PairingNarrow(ctx context.Context, scope Scope, p predicate.Pairing) (predicate.Pairing, error) {
	ps := make([]predicate.Pairing, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.PairingScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return pairing.And(ps...), nil
	}
}

// narrow is [PairingNarrow] with this server's own scope.
func (s PairingServiceServer) narrow(ctx context.Context, p predicate.Pairing) (predicate.Pairing, error) {
	return PairingNarrow(ctx, s.Scope, p)
}

func (s PairingServiceServer) Add(ctx context.Context, req *apptest.PairingAddRequest) (*apptest.Pairing, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *apptest.Pairing), 0, 2)
	q := st.Db.Pairing.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Pairing", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if k, err := RobotGetKey(ctx, st.Db, req.GetLead()); err != nil {
		return nil, err
	} else {
		q.SetLeadID(k)
		ds = append(ds, func(v *apptest.Pairing) {
			v.SetLead(apptest.Robot_builder{Id: k[:]}.Build())
		})
	}
	if k, err := RobotGetKey(ctx, st.Db, req.GetFollow()); err != nil {
		return nil, err
	} else {
		q.SetFollowID(k)
		ds = append(ds, func(v *apptest.Pairing) {
			v.SetFollow(apptest.Robot_builder{Id: k[:]}.Build())
		})
	}
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Pairing already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Pairing: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.PairingService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s PairingServiceServer) Get(ctx context.Context, req *apptest.PairingGetRequest) (*apptest.Pairing, error) {
	p, err := PairingPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Pairing.Query().Where(p)
	PairingSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Pairing not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectPairingKey(q *ent.PairingQuery) {
	q.Select(pairing.FieldID)
}

func PairingSelectedFields(m *apptest.PairingSelect) []string {
	if m.GetAll() {
		return pairing.Columns
	}

	vs := make([]string, 0, len(pairing.Columns))
	{
		vs = append(vs, pairing.FieldID)
	}
	if m.GetDateCreated() {
		vs = append(vs, pairing.FieldDateCreated)
	}

	return vs
}

func PairingSelect(q *ent.PairingQuery, m *apptest.PairingSelect) {
	if !m.GetAll() {
		fields := PairingSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasLead() {
		q.WithLead(func(q *ent.RobotQuery) {
			q.Where(robot.DateErasedIsNil())
			RobotSelect(q, m.GetLead())
		})
	}
	if m.HasFollow() {
		q.WithFollow(func(q *ent.RobotQuery) {
			q.Where(robot.DateErasedIsNil())
			RobotSelect(q, m.GetFollow())
		})
	}
}

func PairingSelectInit(q *ent.PairingQuery, m *apptest.PairingSelect) {
	if m != nil {
		PairingSelect(q, m)
	} else {
		q.WithLead(selectRobotKey)
		q.WithFollow(selectRobotKey)
	}
}

func (s PairingServiceServer) Patch(ctx context.Context, req *apptest.PairingPatchRequest) (*apptest.Pairing, error) {
	doc, err := ormpatch.FromPatchRequest(pairingOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.PairingService_Patch_FullMethodName)
}

func PairingGetKey(ctx context.Context, db *ent.Client, ref *apptest.PairingRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := PairingPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Pairing.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Pairing not found")
		}
		return z, err
	}

	return v, nil
}

var pairingOrmEntity = ormpatch.MustEntityOf(apptest.File_app_robot_proto, "Pairing")

var pairingPatchColumns = entpatch.Columns{
	1: pairing.FieldID, 2: pairing.LeadColumn, 8: pairing.FollowColumn, 15: pairing.FieldDateCreated}

func (s PairingServiceServer) Apply(ctx context.Context, req *apptest.PairingApplyRequest) (*apptest.Pairing, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.PairingService_Apply_FullMethodName)
}

func (s PairingServiceServer) apply(ctx context.Context, ref *apptest.PairingRef, doc *patchpb.Patch, by string) (*apptest.Pairing, error) {
	plan := &ormpatch.Plan{Entity: pairingOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(pairingOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, pairingPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := PairingGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.PairingRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, pairing.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Pairing.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Pairing(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Pairing.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Pairing not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Pairing.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Pairing(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Pairing already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Pairing: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Pairing.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Pairing not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s PairingServiceServer) Erase(ctx context.Context, req *apptest.PairingRef) (*apptest.PairingEraseResponse, error) {
	p, err := PairingPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Pairing.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.PairingEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = pairing.And(p, pairing.IDEQ(v))
	}

	n, err := st.Db.Pairing.Delete().Where(p).Exec(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.PairingService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.PairingEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

func PairingPick(req *apptest.PairingRef) (predicate.Pairing, error) {
	switch req.WhichKey() {
	case apptest.PairingRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return pairing.IDEQ(v), nil
		}
	case apptest.PairingRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Pairing")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type JointServiceServer struct {
	Store

	apptest.UnimplementedJointServiceServer
}

// NewJointServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewJointServiceServer(db *ent.Client, opts ...Option) apptest.JointServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return JointServiceServer{Store: s.Store}
}

// JointNarrow answers with `p` and everything else that narrows a
// read of a Joint: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func JointNarrow(ctx context.Context, scope Scope, p predicate.Joint) (predicate.Joint, error) {
	ps := make([]predicate.Joint, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, joint.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.JointScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return joint.And(ps...), nil
	}
}

// narrow is [JointNarrow] with this server's own scope.
func (s JointServiceServer) narrow(ctx context.Context, p predicate.Joint) (predicate.Joint, error) {
	return JointNarrow(ctx, s.Scope, p)
}

func (s JointServiceServer) Add(ctx context.Context, req *apptest.JointAddRequest) (*apptest.Joint, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *apptest.Joint), 0, 1)
	q := st.Db.Joint.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Joint", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if req.HasRobot() {
		if k, err := RobotGetKey(ctx, st.Db, req.GetRobot()); err != nil {
			return nil, err
		} else {
			q.SetRobotID(k)
			ds = append(ds, func(v *apptest.Joint) {
				v.SetRobot(apptest.Robot_builder{Id: k[:]}.Build())
			})
		}
	}
	q.SetAlias(req.GetAlias())

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Joint already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Joint: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.JointService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s JointServiceServer) Get(ctx context.Context, req *apptest.JointGetRequest) (*apptest.Joint, error) {
	p, err := JointPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Joint.Query().Where(p)
	JointSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Joint not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectJointKey(q *ent.JointQuery) {
	q.Select(joint.FieldID)
}

func JointSelectedFields(m *apptest.JointSelect) []string {
	if m.GetAll() {
		return joint.Columns
	}

	vs := make([]string, 0, len(joint.Columns))
	{
		vs = append(vs, joint.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, joint.FieldAlias)
	}
	if m.GetDateErased() {
		vs = append(vs, joint.FieldDateErased)
	}

	return vs
}

func JointSelect(q *ent.JointQuery, m *apptest.JointSelect) {
	if !m.GetAll() {
		fields := JointSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasRobot() {
		q.WithRobot(func(q *ent.RobotQuery) {
			q.Where(robot.DateErasedIsNil())
			RobotSelect(q, m.GetRobot())
		})
	}
}

func JointSelectInit(q *ent.JointQuery, m *apptest.JointSelect) {
	if m != nil {
		JointSelect(q, m)
	} else {
		q.WithRobot(selectRobotKey)
	}
}

func (s JointServiceServer) Patch(ctx context.Context, req *apptest.JointPatchRequest) (*apptest.Joint, error) {
	doc, err := ormpatch.FromPatchRequest(jointOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.JointService_Patch_FullMethodName)
}

func JointGetKey(ctx context.Context, db *ent.Client, ref *apptest.JointRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := JointPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Joint.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Joint not found")
		}
		return z, err
	}

	return v, nil
}

var jointOrmEntity = ormpatch.MustEntityOf(apptest.File_app_robot_proto, "Joint")

var jointPatchColumns = entpatch.Columns{
	1: joint.FieldID, 2: joint.RobotColumn, 4: joint.FieldAlias, 14: joint.FieldDateErased}

func (s JointServiceServer) Apply(ctx context.Context, req *apptest.JointApplyRequest) (*apptest.Joint, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.JointService_Apply_FullMethodName)
}

func (s JointServiceServer) apply(ctx context.Context, ref *apptest.JointRef, doc *patchpb.Patch, by string) (*apptest.Joint, error) {
	plan := &ormpatch.Plan{Entity: jointOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(jointOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, jointPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := JointGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.JointRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, joint.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Joint.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Joint(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Joint.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Joint not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Joint.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Joint(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Joint already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Joint: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Joint.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Joint not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s JointServiceServer) Erase(ctx context.Context, req *apptest.JointRef) (*apptest.JointEraseResponse, error) {
	p, err := JointPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Joint.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.JointEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = joint.And(p, joint.IDEQ(v))
	}

	u := st.Db.Joint.Update().Where(p)
	u.SetDateErased(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.JointService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.JointEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// JointPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Joint is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasJointWith`, where no narrowing of a Joint
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func JointPick(req *apptest.JointRef) (predicate.Joint, error) {
	p, err := pickJoint(req)
	if err != nil {
		return nil, err
	}

	return joint.And(joint.DateErasedIsNil(), p), nil
}

func pickJoint(req *apptest.JointRef) (predicate.Joint, error) {
	switch req.WhichKey() {
	case apptest.JointRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return joint.IDEQ(v), nil
		}
	case apptest.JointRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Joint")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type FleetServiceServer struct {
	Store

	apptest.UnimplementedFleetServiceServer
}

// NewFleetServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewFleetServiceServer(db *ent.Client, opts ...Option) apptest.FleetServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return FleetServiceServer{Store: s.Store}
}

// FleetNarrow answers with `p` and everything else that narrows a
// read of a Fleet: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func FleetNarrow(ctx context.Context, scope Scope, p predicate.Fleet) (predicate.Fleet, error) {
	ps := make([]predicate.Fleet, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, fleet.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.FleetScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return fleet.And(ps...), nil
	}
}

// narrow is [FleetNarrow] with this server's own scope.
func (s FleetServiceServer) narrow(ctx context.Context, p predicate.Fleet) (predicate.Fleet, error) {
	return FleetNarrow(ctx, s.Scope, p)
}

func (s FleetServiceServer) Add(ctx context.Context, req *apptest.FleetAddRequest) (*apptest.Fleet, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	q := st.Db.Fleet.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Fleet", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	q.SetAlias(req.GetAlias())

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Fleet already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Fleet: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.FleetService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return u.Proto(), nil
}

func (s FleetServiceServer) Get(ctx context.Context, req *apptest.FleetGetRequest) (*apptest.Fleet, error) {
	p, err := FleetPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Fleet.Query().Where(p)
	FleetSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Fleet not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectFleetKey(q *ent.FleetQuery) {
	q.Select(fleet.FieldID)
}

func FleetSelectedFields(m *apptest.FleetSelect) []string {
	if m.GetAll() {
		return fleet.Columns
	}

	vs := make([]string, 0, len(fleet.Columns))
	{
		vs = append(vs, fleet.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, fleet.FieldAlias)
	}
	if m.GetDateErased() {
		vs = append(vs, fleet.FieldDateErased)
	}

	return vs
}

func FleetSelect(q *ent.FleetQuery, m *apptest.FleetSelect) {
	if !m.GetAll() {
		fields := FleetSelectedFields(m)
		q.Select(fields...)
	}
}

func FleetSelectInit(q *ent.FleetQuery, m *apptest.FleetSelect) {
	if m != nil {
		FleetSelect(q, m)
	} else {
	}
}

func (s FleetServiceServer) Patch(ctx context.Context, req *apptest.FleetPatchRequest) (*apptest.Fleet, error) {
	doc, err := ormpatch.FromPatchRequest(fleetOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.FleetService_Patch_FullMethodName)
}

func FleetGetKey(ctx context.Context, db *ent.Client, ref *apptest.FleetRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := FleetPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Fleet.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Fleet not found")
		}
		return z, err
	}

	return v, nil
}

var fleetOrmEntity = ormpatch.MustEntityOf(apptest.File_app_robot_proto, "Fleet")

var fleetPatchColumns = entpatch.Columns{
	1: fleet.FieldID, 4: fleet.FieldAlias, 14: fleet.FieldDateErased}

func (s FleetServiceServer) Apply(ctx context.Context, req *apptest.FleetApplyRequest) (*apptest.Fleet, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.FleetService_Apply_FullMethodName)
}

func (s FleetServiceServer) apply(ctx context.Context, ref *apptest.FleetRef, doc *patchpb.Patch, by string) (*apptest.Fleet, error) {
	plan := &ormpatch.Plan{Entity: fleetOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(fleetOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, fleetPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := FleetGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.FleetRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, fleet.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Fleet.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Fleet(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Fleet.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Fleet not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Fleet.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Fleet(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Fleet already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Fleet: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Fleet.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Fleet not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s FleetServiceServer) Erase(ctx context.Context, req *apptest.FleetRef) (*apptest.FleetEraseResponse, error) {
	p, err := FleetPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Fleet.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.FleetEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = fleet.And(p, fleet.IDEQ(v))
	}

	u := st.Db.Fleet.Update().Where(p)
	u.SetDateErased(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.FleetService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.FleetEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// FleetPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Fleet is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasFleetWith`, where no narrowing of a Fleet
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func FleetPick(req *apptest.FleetRef) (predicate.Fleet, error) {
	p, err := pickFleet(req)
	if err != nil {
		return nil, err
	}

	return fleet.And(fleet.DateErasedIsNil(), p), nil
}

func pickFleet(req *apptest.FleetRef) (predicate.Fleet, error) {
	switch req.WhichKey() {
	case apptest.FleetRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return fleet.IDEQ(v), nil
		}
	case apptest.FleetRef_Alias_case:
		return fleet.AliasEQ(req.GetAlias()), nil
	case apptest.FleetRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Fleet")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type ReadingServiceServer struct {
	Store

	apptest.UnimplementedReadingServiceServer
}

// NewReadingServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewReadingServiceServer(db *ent.Client, opts ...Option) apptest.ReadingServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return ReadingServiceServer{Store: s.Store}
}

// ReadingNarrow answers with `p` and everything else that narrows a
// read of a Reading, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func ReadingNarrow(ctx context.Context, scope Scope, p predicate.Reading) (predicate.Reading, error) {
	ps := make([]predicate.Reading, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.ReadingScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return reading.And(ps...), nil
	}
}

// narrow is [ReadingNarrow] with this server's own scope.
func (s ReadingServiceServer) narrow(ctx context.Context, p predicate.Reading) (predicate.Reading, error) {
	return ReadingNarrow(ctx, s.Scope, p)
}

func (s ReadingServiceServer) Add(ctx context.Context, req *apptest.ReadingAddRequest) (*apptest.Reading, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *apptest.Reading), 0, 1)
	q := st.Db.Reading.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Reading", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if k, err := RobotGetKey(ctx, st.Db, req.GetRobot()); err != nil {
		return nil, err
	} else {
		q.SetRobotID(k)
		ds = append(ds, func(v *apptest.Reading) {
			v.SetRobot(apptest.Robot_builder{Id: k[:]}.Build())
		})
	}
	if v, err := uuid.FromBytes(req.GetTenantId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "tenant_id: %s", err)
	} else {
		q.SetTenantID(v)
	}
	q.SetCelsius(req.GetCelsius())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Reading already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Reading: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.ReadingService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s ReadingServiceServer) Get(ctx context.Context, req *apptest.ReadingGetRequest) (*apptest.Reading, error) {
	p, err := ReadingPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Reading.Query().Where(p)
	ReadingSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Reading not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectReadingKey(q *ent.ReadingQuery) {
	q.Select(reading.FieldID)
}

func ReadingSelectedFields(m *apptest.ReadingSelect) []string {
	if m.GetAll() {
		return reading.Columns
	}

	vs := make([]string, 0, len(reading.Columns))
	{
		vs = append(vs, reading.FieldID)
	}
	if m.GetTenantId() {
		vs = append(vs, reading.FieldTenantID)
	}
	if m.GetCelsius() {
		vs = append(vs, reading.FieldCelsius)
	}
	if m.GetDateCreated() {
		vs = append(vs, reading.FieldDateCreated)
	}

	return vs
}

func ReadingSelect(q *ent.ReadingQuery, m *apptest.ReadingSelect) {
	if !m.GetAll() {
		fields := ReadingSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasRobot() {
		q.WithRobot(func(q *ent.RobotQuery) {
			q.Where(robot.DateErasedIsNil())
			RobotSelect(q, m.GetRobot())
		})
	}
}

func ReadingSelectInit(q *ent.ReadingQuery, m *apptest.ReadingSelect) {
	if m != nil {
		ReadingSelect(q, m)
	} else {
		q.WithRobot(selectRobotKey)
	}
}

func (s ReadingServiceServer) Patch(ctx context.Context, req *apptest.ReadingPatchRequest) (*apptest.Reading, error) {
	doc, err := ormpatch.FromPatchRequest(readingOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.ReadingService_Patch_FullMethodName)
}

func ReadingGetKey(ctx context.Context, db *ent.Client, ref *apptest.ReadingRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := ReadingPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Reading.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Reading not found")
		}
		return z, err
	}

	return v, nil
}

var readingOrmEntity = ormpatch.MustEntityOf(apptest.File_app_robot_proto, "Reading")

var readingPatchColumns = entpatch.Columns{
	1: reading.FieldID, 2: reading.RobotColumn, 9: reading.FieldTenantID, 8: reading.FieldCelsius, 15: reading.FieldDateCreated}

func (s ReadingServiceServer) Apply(ctx context.Context, req *apptest.ReadingApplyRequest) (*apptest.Reading, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.ReadingService_Apply_FullMethodName)
}

func (s ReadingServiceServer) apply(ctx context.Context, ref *apptest.ReadingRef, doc *patchpb.Patch, by string) (*apptest.Reading, error) {
	plan := &ormpatch.Plan{Entity: readingOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(readingOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, readingPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := ReadingGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.ReadingRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, reading.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Reading.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Reading(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Reading.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Reading not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Reading.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Reading(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Reading already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Reading: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Reading.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Reading not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s ReadingServiceServer) Erase(ctx context.Context, req *apptest.ReadingRef) (*apptest.ReadingEraseResponse, error) {
	p, err := ReadingPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Reading.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.ReadingEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = reading.And(p, reading.IDEQ(v))
	}

	n, err := st.Db.Reading.Delete().Where(p).Exec(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.ReadingService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.ReadingEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

func ReadingPick(req *apptest.ReadingRef) (predicate.Reading, error) {
	switch req.WhichKey() {
	case apptest.ReadingRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return reading.IDEQ(v), nil
		}
	case apptest.ReadingRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Reading")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
