// protoc-gen-pd writes what a payday schema declared into the code that
// enforces it.
//
// It reads the `(payday.entity)` option beside what `orm` already says, and
// emits one file holding the domain of each entity, the minter that stamps
// identifiers with it, and the wall that narrows every read to the tenants a
// caller may see.
//
// It also **refuses to generate** a schema that left any of those unsaid. That
// is the half worth having: an entity with no domain hands out identifiers that
// say nothing, and an entity that never said whether it is behind the wall sits
// outside it while everything goes on compiling.
//
//	plugins:
//	  - local: [go, tool, github.com/lesomnus/payday/cmd/protoc-gen-pd]
//	    out: .
//	    opt:
//	      - module=github.com/acme/app
//	      - ent=internal/ent
//	      - bare=server/bare
//	      - out=server/pd
//	    strategy: all
//
// `strategy: all` is not optional. The default runs a plugin once per
// directory, and an entity whose tenant is declared in another one is then not
// a generation target when its own file is read.
package main

import (
	"context"
	"flag"
	"fmt"
	"path"
	"strings"

	"github.com/protobuf-orm/protobuf-orm/graph"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/lesomnus/payday/internal/pdgen"
)

type opts struct {
	// Ent and Bare are where the other generators were told to put the ent
	// runtime and the generated servers, relative to the module root.
	Ent  string
	Bare string

	// Out is where this plugin's own file goes.
	Out  string
	Name string
}

func main() {
	o := opts{
		Ent:  "internal/ent",
		Bare: "server/bare",
		Out:  "server/pd",
		Name: "pd.g.go",
	}

	var fs flag.FlagSet
	fs.StringVar(&o.Ent, "ent", o.Ent, "directory of the ent runtime, relative to the module root")
	fs.StringVar(&o.Bare, "bare", o.Bare, "directory of the generated servers")
	fs.StringVar(&o.Out, "out", o.Out, "directory this plugin writes into")
	fs.StringVar(&o.Name, "name", o.Name, "name of the file this plugin writes")

	protogen.Options{ParamFunc: fs.Set}.Run(func(p *protogen.Plugin) error {
		return run(context.Background(), p, o)
	})
}

func run(ctx context.Context, p *protogen.Plugin, o opts) error {
	p.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO2
	p.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_MAX
	p.SupportedFeatures = uint64(0 |
		pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL |
		pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS,
	)

	g := graph.NewGraph()
	if err := graph.ParseFiles(ctx, g, p.Files); err != nil {
		return fmt.Errorf("read the schema: %w", err)
	}

	s, err := pdgen.Read(g, p.Files)
	if err != nil {
		return err
	}
	if len(s.Entities) == 0 {
		return nil
	}

	// The module root is where the message package lives, and everything else
	// is named relative to it -- the same way the orm generators are told
	// about it.
	src := sourceOf(p, s)
	if src == nil {
		return fmt.Errorf("no file to take the module path from")
	}

	root := src.GoImportPath
	paths := pdgen.Paths{
		Ent:  root + protogen.GoImportPath("/"+o.Ent),
		Bare: root + protogen.GoImportPath("/"+o.Bare),
	}

	out := p.NewGeneratedFile(path.Join(o.Out, o.Name), root+protogen.GoImportPath("/"+o.Out))
	out.P("// Code generated by protoc-gen-pd. DO NOT EDIT.")
	out.P("")
	out.P("// Package ", pkgName(o.Out), " is what the schema said, as code.")
	out.P("//")
	out.P("// Nothing here is a decision. Every line follows from a `(payday.entity)`")
	out.P("// option, and the reason it is generated rather than written is that the")
	out.P("// line nobody writes is the one that matters -- an entity added to the")
	out.P("// schema arrives here with its wall already on it.")
	out.P("package ", pkgName(o.Out))
	out.P("")

	pdgen.EmitDomains(out, s)
	pdgen.EmitMinter(out, s, paths)
	pdgen.EmitWall(out, s, paths)

	return nil
}

// sourceOf answers with a file that holds an entity, which is what the module
// path is read from.
func sourceOf(p *protogen.Plugin, s *pdgen.Schema) *protogen.File {
	want := map[string]bool{}
	for _, v := range s.Entities {
		want[string(v.FullName())] = true
	}

	for _, f := range p.Files {
		if !f.Generate {
			continue
		}
		for _, m := range f.Messages {
			if want[string(m.Desc.FullName())] {
				return f
			}
		}
	}

	return nil
}

func pkgName(dir string) string {
	vs := strings.Split(strings.Trim(dir, "/"), "/")
	return vs[len(vs)-1]
}
