package pdgen

import (
	"google.golang.org/protobuf/compiler/protogen"

	"github.com/lesomnus/payday/pdpb"
)

var (
	pkgTrail     = protogen.GoImportPath("github.com/lesomnus/payday/trail")
	pkgProtojson = protogen.GoImportPath("google.golang.org/protobuf/encoding/protojson")
)

// EmitTrail writes the app's half of the retention policy: the audit table, as
// much of it as `trail` needs to move rows out of the database.
//
// It is generated rather than written in the runtime for the reason the outbox
// drain is -- `ent.Client` and its predicates are the app's types and payday
// cannot name them, and payday has no Go type for its own `Audit` either, since
// the schema is **copied** into each app and generated there.
//
// What is not generated is any judgement. There is none here beyond *read a
// batch of these rows older than this, say which tenants rows are filed under,
// and forget or blank the ones I name*: the two clocks, whose clock a row is
// on, what a hold keeps, the refusal to destroy what was never written, the
// archive's layout and what may be destroyed are all in the runtime, where they
// can be argued with once instead of per app. Even the rule for which tenants a
// row names is the runtime's -- `trail.TenantsOf` -- and this hands it the
// three columns.
//
// Which is why erasing one subject is not generated either, though it was:
// `pd.ForgetInTrail` blanked two columns for a set the caller chose, and once a
// legal hold could be on some of those rows, which of them was a judgement.
// It is `trail.Policy.Forget`, and this is the `Blank` it calls.
//
// The document that travels between the two halves is protojson, which is the
// archive's format anyway -- *readable by anything that can read an `Audit`*.
func EmitTrail(g *protogen.GeneratedFile, s *Schema, p Paths, root protogen.GoImportPath) {
	// Refused by [CheckOwn] before this, for a real app; see there.
	if !s.Has(pdpb.Own_OWN_AUDIT) {
		return
	}

	v := s.Own(pdpb.Own_OWN_AUDIT)
	e := v.GoName()
	entPkg := p.Ent + "/" + protogen.GoImportPath(v.EntPkg())
	pred := p.Ent + "/predicate"

	g.P("// TrailStore is the audit table as [trail.Store] sees it.")
	g.P("//")
	g.P("// Handed to `trail.Sweep` beside a policy, and to whatever command an app")
	g.P("// gives an operator:")
	g.P("//")
	g.P("//	s.Spin = append(s.Spin, trail.Sweep(pd.TrailStore(db), policy))")
	g.P("func TrailStore(db *", p.Ent.Ident("Client"), ") ", pkgTrail.Ident("Store"), " {")
	g.P("	return trailStore{db}")
	g.P("}")
	g.P("")
	g.P("type trailStore struct{ db *", p.Ent.Ident("Client"), " }")
	g.P("")
	g.P("var _ ", pkgTrail.Ident("Store"), " = trailStore{}")
	g.P("")

	g.P("// of narrows to the kinds a read is about, and to whose rows they are.")
	g.P("//")
	g.P("// By the `domain` column and not by the domain byte inside `object_id`,")
	g.P("// which carries the same fact and cannot be indexed: *what kind was this")
	g.P("// row about* is answered by reading a row, and *which rows were about")
	g.P("// robots* is a query over a set. The second is what a retention policy is")
	g.P("// made of.")
	g.P("//")
	g.P("// And by the three tenant columns, which are what the wall on the trail")
	g.P("// reads: a row is readable by every tenant it names, and so it is on each")
	g.P("// of their windows.")
	g.P("func (s trailStore) of(k ", pkgTrail.Ident("Scope"), ") *", p.Ent.Ident(e+"Query"), " {")
	g.P("	q := s.db.", e, ".Query()")
	g.P("	if len(k.Only) > 0 {")
	g.P("		q = q.Where(", entPkg.Ident("DomainIn"), "(numbers(k.Only)...))")
	g.P("	} else if len(k.Except) > 0 {")
	g.P("		q = q.Where(", entPkg.Ident("DomainNotIn"), "(numbers(k.Except)...))")
	g.P("	}")
	g.P("")
	g.P("	if len(k.Objects) > 0 {")
	g.P("		ids := make([]", pkgUuid.Ident("UUID"), ", len(k.Objects))")
	g.P("		for i, v := range k.Objects {")
	g.P("			ids[i] = v.Uuid()")
	g.P("		}")
	g.P("")
	g.P("		q = q.Where(", entPkg.Ident("ObjectIdIn"), "(ids...))")
	g.P("	}")
	g.P("")
	g.P("	t := k.Tenant.Uuid()")
	g.P("	switch k.Whose {")
	g.P("	case ", pkgTrail.Ident("FiledUnder"), ":")
	g.P("		q = q.Where(", entPkg.Ident("TenantIdEQ"), "(t))")
	g.P("	case ", pkgTrail.Ident("Alone"), ":")
	g.P("		q = q.Where(trailAlone(t))")
	g.P("	case ", pkgTrail.Ident("Together"), ":")
	g.P("		q = q.Where(")
	g.P("			", entPkg.Ident("Or"), "(", entPkg.Ident("TenantIdEQ"), "(t), ",
		entPkg.Ident("ActorTenantIdEQ"), "(t), ", entPkg.Ident("CounterpartTenantIdEQ"), "(t)),")
	g.P("			", entPkg.Ident("Not"), "(trailAlone(t)),")
	g.P("		)")
	g.P("	case ", pkgTrail.Ident("Sharing"), ":")
	g.P("		q = q.Where(", entPkg.Ident("TenantIdEQ"), "(t), ", entPkg.Ident("Not"), "(trailAlone(t)))")
	g.P("	}")
	g.P("")
	g.P("	return q")
	g.P("}")
	g.P("")

	g.P("// trailAlone is a row filed under `t` that names no other tenant: the actor")
	g.P("// is of `t` or is nobody, and so is the other party if there is one. Nobody")
	g.P("// is the zero identifier -- the deployment, writing to itself.")
	g.P("func trailAlone(t ", pkgUuid.Ident("UUID"), ") ", pred.Ident(e), " {")
	g.P("	none := ", pkgUuid.Ident("Nil"), "()")
	g.P("")
	g.P("	return ", entPkg.Ident("And"), "(")
	g.P("		", entPkg.Ident("TenantIdEQ"), "(t),")
	g.P("		", entPkg.Ident("ActorTenantIdIn"), "(t, none),")
	g.P("		", entPkg.Ident("Or"), "(", entPkg.Ident("CounterpartTenantIdIsNil"), "(), ",
		entPkg.Ident("CounterpartTenantIdIn"), "(t, none)),")
	g.P("	)")
	g.P("}")
	g.P("")

	g.P("// Tenants is one seek per tenant: the next `tenant_id` after the last, which")
	g.P("// the index on `(tenant_id, date_created)` answers without reading the rows")
	g.P("// in between. A `DISTINCT` would read all of them.")
	g.P("func (s trailStore) Tenants(ctx ", pkgCtx.Ident("Context"), ", after ", pkgPdid.Ident("Id"),
		", limit int) ([]", pkgPdid.Ident("Id"), ", error) {")
	g.P("	out := []", pkgPdid.Ident("Id"), "{}")
	g.P("	last := after.Uuid()")
	g.P("	for len(out) < limit {")
	g.P("		v, err := s.db.", e, ".Query().")
	g.P("			Where(", entPkg.Ident("TenantIdGT"), "(last)).")
	g.P("			Order(", p.Ent.Ident("Asc"), "(", entPkg.Ident("FieldTenantId"), ")).")
	g.P("			First(ctx)")
	g.P("		if ", p.Ent.Ident("IsNotFound"), "(err) {")
	g.P("			break")
	g.P("		}")
	g.P("		if err != nil {")
	g.P("			return out, err")
	g.P("		}")
	g.P("")
	g.P("		out = append(out, ", pkgPdid.Ident("Id"), "(v.TenantId))")
	g.P("		last = v.TenantId")
	g.P("	}")
	g.P("")
	g.P("	return out, nil")
	g.P("}")
	g.P("")

	g.P("// older is a scope's rows written before `at`, past `after`, oldest first.")
	g.P("func (s trailStore) older(k ", pkgTrail.Ident("Scope"), ", at ", pkgTime.Ident("Time"),
		", after ", pkgTrail.Ident("Cursor"), ", limit int) (*", p.Ent.Ident(e+"Query"), ", error) {")
	g.P("	q := s.of(k).Where(", entPkg.Ident("DateCreatedLT"), "(at))")
	g.P("	if after.Key != nil {")
	g.P("		id, ok := after.Key.(", pkgUuid.Ident("UUID"), ")")
	g.P("		if !ok {")
	g.P("			return nil, ", pkgFmt.Ident("Errorf"), "(\"trail: %T is not a key this store gave out\", after.Key)")
	g.P("		}")
	g.P("")
	g.P("		q = q.Where(", entPkg.Ident("Or"), "(")
	g.P("			", entPkg.Ident("DateCreatedGT"), "(after.Created),")
	g.P("			", entPkg.Ident("And"), "(", entPkg.Ident("DateCreatedEQ"), "(after.Created), ",
		entPkg.Ident("IdGT"), "(id)),")
	g.P("		))")
	g.P("	}")
	g.P("")
	g.P("	return q.")
	g.P("		Order(", p.Ent.Ident("Asc"), "(", entPkg.Ident("FieldDateCreated"),
		", ", entPkg.Ident("FieldId"), ")).")
	g.P("		Limit(limit), nil")
	g.P("}")
	g.P("")
	g.P("func (s trailStore) Older(ctx ", pkgCtx.Ident("Context"), ", k ", pkgTrail.Ident("Scope"),
		", at ", pkgTime.Ident("Time"), ", after ", pkgTrail.Ident("Cursor"), ", limit int) (",
		pkgTrail.Ident("Rows"), ", error) {")
	g.P("	q, err := s.older(k, at, after, limit)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("")
	g.P("	vs, err := q.All(ctx)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("")
	g.P("	out := make(", pkgTrail.Ident("Rows"), ", 0, len(vs))")
	g.P("	for _, v := range vs {")
	// `Proto()` rather than a conversion written here, so that a column an app
	// added to the trail is in the archive too. See the note on 3 and 19+ in
	// payday's audit.proto.
	g.P("		b, err := ", pkgProtojson.Ident("Marshal"), "(v.Proto())")
	g.P("		if err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("")
	g.P("		out = append(out, ", pkgTrail.Ident("Row"), "{")
	g.P("			Doc:     b,")
	g.P("			Key:     v.Id,")
	g.P("			Domain:  ", pkgPdid.Ident("Domain"), "(v.Domain),")
	g.P("			Created: v.DateCreated,")
	g.P("			Tenants: ", pkgTrail.Ident("TenantsOf"), "(v.TenantId, v.ActorTenantId, v.CounterpartTenantId),")
	g.P("		})")
	g.P("	}")
	g.P("")
	g.P("	return out, nil")
	g.P("}")
	g.P("")

	g.P("// Heads is the same rows with only what a decision about them reads: no")
	g.P("// `value`, no `patch`, and nothing marshalled.")
	g.P("func (s trailStore) Heads(ctx ", pkgCtx.Ident("Context"), ", k ", pkgTrail.Ident("Scope"),
		", at ", pkgTime.Ident("Time"), ", after ", pkgTrail.Ident("Cursor"), ", limit int) (",
		pkgTrail.Ident("Rows"), ", error) {")
	g.P("	q, err := s.older(k, at, after, limit)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("")
	g.P("	vs, err := q.Select(")
	g.P("		", entPkg.Ident("FieldId"), ",")
	g.P("		", entPkg.Ident("FieldDateCreated"), ",")
	g.P("		", entPkg.Ident("FieldDomain"), ",")
	g.P("		", entPkg.Ident("FieldTenantId"), ",")
	g.P("		", entPkg.Ident("FieldActorTenantId"), ",")
	g.P("		", entPkg.Ident("FieldCounterpartTenantId"), ",")
	g.P("	).All(ctx)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("")
	g.P("	out := make(", pkgTrail.Ident("Rows"), ", 0, len(vs))")
	g.P("	for _, v := range vs {")
	g.P("		out = append(out, ", pkgTrail.Ident("Row"), "{")
	g.P("			Key:     v.Id,")
	g.P("			Domain:  ", pkgPdid.Ident("Domain"), "(v.Domain),")
	g.P("			Created: v.DateCreated,")
	g.P("			Tenants: ", pkgTrail.Ident("TenantsOf"), "(v.TenantId, v.ActorTenantId, v.CounterpartTenantId),")
	g.P("		})")
	g.P("	}")
	g.P("")
	g.P("	return out, nil")
	g.P("}")
	g.P("")
	g.P("func (s trailStore) Count(ctx ", pkgCtx.Ident("Context"), ", k ", pkgTrail.Ident("Scope"),
		", at ", pkgTime.Ident("Time"), ") (int, error) {")
	g.P("	return s.of(k).Where(", entPkg.Ident("DateCreatedLT"), "(at)).Count(ctx)")
	g.P("}")
	g.P("")

	g.P("// Forget removes exactly the rows these keys name.")
	g.P("//")
	g.P("// By identifier and not by the cutoff again, which is the whole of what")
	g.P("// makes the archive trustworthy: a second query matches whatever is true")
	g.P("// when it runs, and a row backdated by a clock that stepped is one it")
	g.P("// removes and the archive does not have.")
	g.P("func (s trailStore) Forget(ctx ", pkgCtx.Ident("Context"), ", keys []any) (int, error) {")
	g.P("	ids, err := trailKeys(keys)")
	g.P("	if err != nil {")
	g.P("		return 0, err")
	g.P("	}")
	g.P("")
	g.P("	return s.db.", e, ".Delete().Where(", entPkg.Ident("IdIn"), "(ids...)).Exec(ctx)")
	g.P("}")
	g.P("")
	g.P("// Blank empties the two columns that hold contents, for exactly these rows.")
	g.P("//")
	g.P("// Empty and not nil: nil is SQL NULL, which a NOT NULL column refuses on")
	g.P("// PostgreSQL and accepts on SQLite.")
	g.P("func (s trailStore) Blank(ctx ", pkgCtx.Ident("Context"), ", keys []any) (int, error) {")
	g.P("	ids, err := trailKeys(keys)")
	g.P("	if err != nil {")
	g.P("		return 0, err")
	g.P("	}")
	g.P("")
	g.P("	return s.db.", e, ".Update().")
	g.P("		Where(", entPkg.Ident("IdIn"), "(ids...)).")
	g.P("		SetValue([]byte{}).")
	g.P("		SetPatch([]byte{}).")
	g.P("		Save(ctx)")
	g.P("}")
	g.P("")
	g.P("// trailKeys is the keys this store gave out, back as what it deletes by.")
	g.P("func trailKeys(keys []any) ([]", pkgUuid.Ident("UUID"), ", error) {")
	g.P("	ids := make([]", pkgUuid.Ident("UUID"), ", 0, len(keys))")
	g.P("	for _, k := range keys {")
	g.P("		v, ok := k.(", pkgUuid.Ident("UUID"), ")")
	g.P("		if !ok {")
	g.P("			return nil, ", pkgFmt.Ident("Errorf"), "(\"trail: %T is not a key this store gave out\", k)")
	g.P("		}")
	g.P("")
	g.P("		ids = append(ids, v)")
	g.P("	}")
	g.P("")
	g.P("	return ids, nil")
	g.P("}")
	g.P("")

	g.P("// numbers is what the column holds, which is a domain widened to what")
	g.P("// protobuf has: there is no `uint8`.")
	g.P("func numbers(ds []", pkgPdid.Ident("Domain"), ") []uint32 {")
	g.P("	out := make([]uint32, len(ds))")
	g.P("	for i, d := range ds {")
	g.P("		out[i] = uint32(d)")
	g.P("	}")
	g.P("")
	g.P("	return out")
	g.P("}")
	g.P("")

	g.P("// TrailOf is a reader of the archive's documents as the messages they hold:")
	g.P("// what `trail.Read`, `trail.ReadTenant` and `trail.ReadFiles` are handed.")
	g.P("//")
	g.P("//	err := trail.Read(ctx, archive, pd.TrailOf(func(v *app.", e, ") error {")
	g.P("//		...")
	g.P("//	}))")
	g.P("//")
	g.P("// The runtime hands over documents, because it has no `", e, "` type to")
	g.P("// unmarshal into. This is the half that does.")
	g.P("//")
	g.P("// It opens no database, deliberately: what an archive is for is outliving")
	g.P("// the deployment that wrote it, and a reader that needed the deployment")
	g.P("// would be answering the question at the one moment nobody can.")
	g.P("func TrailOf(fn func(*", root.Ident(e), ") error) func(doc []byte) error {")
	g.P("	return func(doc []byte) error {")
	g.P("		v := &", root.Ident(e), "{}")
	g.P("		if err := ", pkgProtojson.Ident("Unmarshal"), "(doc, v); err != nil {")
	g.P("			return err")
	g.P("		}")
	g.P("")
	g.P("		return fn(v)")
	g.P("	}")
	g.P("}")
	g.P("")
}
