// Code generated by ent, DO NOT EDIT.

package fleet

import (
	"github.com/protobuf-orm/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the fleet type in the database.
	Label = "fleet"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldDateErased holds the string denoting the date_erased field in the database.
	FieldDateErased = "date_erased"
	// Table holds the table name of the fleet in the database.
	Table = "fleet"
)

// Columns holds all SQL columns for fleet fields.
var Columns = []string{
	FieldId,
	FieldAlias,
	FieldDateErased,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Fleet queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}

// ByDateErased orders the results by the date_erased field.
func ByDateErased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateErased, opts...).ToFunc()
}
