// Code generated by ent, DO NOT EDIT.

package fleet

import (
	"time"
	"uuid"

	"github.com/lesomnus/payday/internal/apptest/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.Fleet {
	return predicate.Fleet(sql.FieldLTE(FieldId, id))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldEQ(FieldAlias, v))
}

// DateErased applies equality check predicate on the "date_erased" field. It's identical to DateErasedEQ.
func DateErased(v time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldEQ(FieldDateErased, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.Fleet {
	return predicate.Fleet(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.Fleet {
	return predicate.Fleet(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.Fleet {
	return predicate.Fleet(sql.FieldContainsFold(FieldAlias, v))
}

// DateErasedEQ applies the EQ predicate on the "date_erased" field.
func DateErasedEQ(v time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldEQ(FieldDateErased, v))
}

// DateErasedNEQ applies the NEQ predicate on the "date_erased" field.
func DateErasedNEQ(v time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldNEQ(FieldDateErased, v))
}

// DateErasedIn applies the In predicate on the "date_erased" field.
func DateErasedIn(vs ...time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldIn(FieldDateErased, vs...))
}

// DateErasedNotIn applies the NotIn predicate on the "date_erased" field.
func DateErasedNotIn(vs ...time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldNotIn(FieldDateErased, vs...))
}

// DateErasedGT applies the GT predicate on the "date_erased" field.
func DateErasedGT(v time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldGT(FieldDateErased, v))
}

// DateErasedGTE applies the GTE predicate on the "date_erased" field.
func DateErasedGTE(v time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldGTE(FieldDateErased, v))
}

// DateErasedLT applies the LT predicate on the "date_erased" field.
func DateErasedLT(v time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldLT(FieldDateErased, v))
}

// DateErasedLTE applies the LTE predicate on the "date_erased" field.
func DateErasedLTE(v time.Time) predicate.Fleet {
	return predicate.Fleet(sql.FieldLTE(FieldDateErased, v))
}

// DateErasedIsNil applies the IsNil predicate on the "date_erased" field.
func DateErasedIsNil() predicate.Fleet {
	return predicate.Fleet(sql.FieldIsNull(FieldDateErased))
}

// DateErasedNotNil applies the NotNil predicate on the "date_erased" field.
func DateErasedNotNil() predicate.Fleet {
	return predicate.Fleet(sql.FieldNotNull(FieldDateErased))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Fleet) predicate.Fleet {
	return predicate.Fleet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Fleet) predicate.Fleet {
	return predicate.Fleet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Fleet) predicate.Fleet {
	return predicate.Fleet(sql.NotPredicates(p))
}
