// Code generated by ent, DO NOT EDIT.

package joint

import (
	"time"
	"uuid"

	"github.com/lesomnus/payday/internal/apptest/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.JointOrErr(sql.FieldEQ(FieldId, vc), err)
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.JointOrErr(sql.FieldEQ(FieldId, vc), err)
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.JointOrErr(sql.FieldNEQ(FieldId, vc), err)
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.Joint {
	var (
		err error
		vcs = make([]any, len(ids))
	)
	for i := range vcs {
		if vcs[i], err = ValueScanner.Id.Value(ids[i]); err != nil {
			break
		}
	}
	return predicate.JointOrErr(sql.FieldIn(FieldId, vcs...), err)
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.Joint {
	var (
		err error
		vcs = make([]any, len(ids))
	)
	for i := range vcs {
		if vcs[i], err = ValueScanner.Id.Value(ids[i]); err != nil {
			break
		}
	}
	return predicate.JointOrErr(sql.FieldNotIn(FieldId, vcs...), err)
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.JointOrErr(sql.FieldGT(FieldId, vc), err)
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.JointOrErr(sql.FieldGTE(FieldId, vc), err)
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.JointOrErr(sql.FieldLT(FieldId, vc), err)
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.JointOrErr(sql.FieldLTE(FieldId, vc), err)
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.Joint {
	return predicate.Joint(sql.FieldEQ(FieldAlias, v))
}

// DateErased applies equality check predicate on the "date_erased" field. It's identical to DateErasedEQ.
func DateErased(v time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldEQ(FieldDateErased, v))
}

// RobotId applies equality check predicate on the "robot_id" field. It's identical to RobotIdEQ.
func RobotId(v uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.RobotId.Value(v)
	return predicate.JointOrErr(sql.FieldEQ(FieldRobotId, vc), err)
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.Joint {
	return predicate.Joint(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.Joint {
	return predicate.Joint(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.Joint {
	return predicate.Joint(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.Joint {
	return predicate.Joint(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.Joint {
	return predicate.Joint(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.Joint {
	return predicate.Joint(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.Joint {
	return predicate.Joint(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.Joint {
	return predicate.Joint(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.Joint {
	return predicate.Joint(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.Joint {
	return predicate.Joint(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.Joint {
	return predicate.Joint(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.Joint {
	return predicate.Joint(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.Joint {
	return predicate.Joint(sql.FieldContainsFold(FieldAlias, v))
}

// DateErasedEQ applies the EQ predicate on the "date_erased" field.
func DateErasedEQ(v time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldEQ(FieldDateErased, v))
}

// DateErasedNEQ applies the NEQ predicate on the "date_erased" field.
func DateErasedNEQ(v time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldNEQ(FieldDateErased, v))
}

// DateErasedIn applies the In predicate on the "date_erased" field.
func DateErasedIn(vs ...time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldIn(FieldDateErased, vs...))
}

// DateErasedNotIn applies the NotIn predicate on the "date_erased" field.
func DateErasedNotIn(vs ...time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldNotIn(FieldDateErased, vs...))
}

// DateErasedGT applies the GT predicate on the "date_erased" field.
func DateErasedGT(v time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldGT(FieldDateErased, v))
}

// DateErasedGTE applies the GTE predicate on the "date_erased" field.
func DateErasedGTE(v time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldGTE(FieldDateErased, v))
}

// DateErasedLT applies the LT predicate on the "date_erased" field.
func DateErasedLT(v time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldLT(FieldDateErased, v))
}

// DateErasedLTE applies the LTE predicate on the "date_erased" field.
func DateErasedLTE(v time.Time) predicate.Joint {
	return predicate.Joint(sql.FieldLTE(FieldDateErased, v))
}

// DateErasedIsNil applies the IsNil predicate on the "date_erased" field.
func DateErasedIsNil() predicate.Joint {
	return predicate.Joint(sql.FieldIsNull(FieldDateErased))
}

// DateErasedNotNil applies the NotNil predicate on the "date_erased" field.
func DateErasedNotNil() predicate.Joint {
	return predicate.Joint(sql.FieldNotNull(FieldDateErased))
}

// RobotIdEQ applies the EQ predicate on the "robot_id" field.
func RobotIdEQ(v uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.RobotId.Value(v)
	return predicate.JointOrErr(sql.FieldEQ(FieldRobotId, vc), err)
}

// RobotIdNEQ applies the NEQ predicate on the "robot_id" field.
func RobotIdNEQ(v uuid.UUID) predicate.Joint {
	vc, err := ValueScanner.RobotId.Value(v)
	return predicate.JointOrErr(sql.FieldNEQ(FieldRobotId, vc), err)
}

// RobotIdIn applies the In predicate on the "robot_id" field.
func RobotIdIn(vs ...uuid.UUID) predicate.Joint {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.RobotId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.JointOrErr(sql.FieldIn(FieldRobotId, v...), err)
}

// RobotIdNotIn applies the NotIn predicate on the "robot_id" field.
func RobotIdNotIn(vs ...uuid.UUID) predicate.Joint {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.RobotId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.JointOrErr(sql.FieldNotIn(FieldRobotId, v...), err)
}

// RobotIdIsNil applies the IsNil predicate on the "robot_id" field.
func RobotIdIsNil() predicate.Joint {
	return predicate.Joint(sql.FieldIsNull(FieldRobotId))
}

// RobotIdNotNil applies the NotNil predicate on the "robot_id" field.
func RobotIdNotNil() predicate.Joint {
	return predicate.Joint(sql.FieldNotNull(FieldRobotId))
}

// HasRobot applies the HasEdge predicate on the "robot" edge.
func HasRobot() predicate.Joint {
	return predicate.Joint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, RobotTable, RobotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRobotWith applies the HasEdge predicate on the "robot" edge with a given conditions (other predicates).
func HasRobotWith(preds ...predicate.Robot) predicate.Joint {
	return predicate.Joint(func(s *sql.Selector) {
		step := newRobotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Joint) predicate.Joint {
	return predicate.Joint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Joint) predicate.Joint {
	return predicate.Joint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Joint) predicate.Joint {
	return predicate.Joint(sql.NotPredicates(p))
}
