// Code generated by protoc-gen-pd. DO NOT EDIT.

// Package pd is what the schema said, as code.
//
// Nothing here is a decision. Every line follows from a `(payday.entity)`
// option, and the reason it is generated rather than written is that the
// line nobody writes is the one that matters -- an entity added to the
// schema arrives here with its wall already on it.
package pd

import (
	context "context"
	uuid "github.com/google/uuid"
	frame "github.com/lesomnus/payday/frame"
	audit "github.com/lesomnus/payday/internal/apptest/ent/audit"
	cell "github.com/lesomnus/payday/internal/apptest/ent/cell"
	holder "github.com/lesomnus/payday/internal/apptest/ent/holder"
	joint "github.com/lesomnus/payday/internal/apptest/ent/joint"
	predicate "github.com/lesomnus/payday/internal/apptest/ent/predicate"
	robot "github.com/lesomnus/payday/internal/apptest/ent/robot"
	tenant "github.com/lesomnus/payday/internal/apptest/ent/tenant"
	bare "github.com/lesomnus/payday/internal/apptest/server/bare"
	pdid "github.com/lesomnus/payday/pdid"
)

// The domain of each entity, as declared by `(payday.entity).domain`.
//
// A domain outlives the row it named: an identifier read out of an audit
// trail says what kind of thing it was long after the row is gone. So a
// number is chosen once and never given to something else.
const (
	CellDomain   pdid.Domain = 10 // "cell"
	FleetDomain  pdid.Domain = 9  // "fleet"
	JointDomain  pdid.Domain = 8  // "joint"
	RobotDomain  pdid.Domain = 7  // "robot"
	AuditDomain  pdid.Domain = 3  // "audit"
	HolderDomain pdid.Domain = 2  // "holder"
	TenantDomain pdid.Domain = 1  // "tenant"
)

func init() {
	pdid.Register("app.Cell", CellDomain, "cell")
	pdid.Register("app.Fleet", FleetDomain, "fleet")
	pdid.Register("app.Joint", JointDomain, "joint")
	pdid.Register("app.Robot", RobotDomain, "robot")
	pdid.Register("payday.Audit", AuditDomain, "audit")
	pdid.Register("payday.Holder", HolderDomain, "holder")
	pdid.Register("payday.Tenant", TenantDomain, "tenant")
}

// Domains is the domain of each entity by the full name of its message,
// which is the name a [Minter] is asked about.
var Domains = map[string]pdid.Domain{
	"app.Cell":      CellDomain,
	"app.Fleet":     FleetDomain,
	"app.Joint":     JointDomain,
	"app.Robot":     RobotDomain,
	"payday.Audit":  AuditDomain,
	"payday.Holder": HolderDomain,
	"payday.Tenant": TenantDomain,
}

// Minter answers with the [bare.Minter] that gives every new row an
// identifier of its entity's domain, and refuses one of another.
//
// It is asked by name because that is what the generated servers know
// themselves by; an entity nothing declared is refused rather than given
// an identifier that says nothing.
func Minter() bare.Minter {
	return bare.MinterFunc(func(
		_ context.Context, entity string, given uuid.UUID, ok bool,
	) (uuid.UUID, error) {
		d, found := Domains[entity]
		if !found {
			return uuid.Nil, pdid.NoDomain(entity)
		}

		return pdid.Mint(d, given, ok)
	})
}

// Wall answers with the scope that puts every read behind the tenant the
// row belongs to.
//
// It is installed on the innermost server rather than applied in front,
// which reads backwards and is the point: narrowing what a caller may see
// is a predicate, and a predicate belongs in the query. Done from in front
// it is an override of Get, Patch, Apply and Erase, once per entity and
// once more for every entity added afterwards.
//
//	sink, err := bare.NewServer(db, bare.WithScope(pd.Wall()))
//
// Narrowing is not refusing. A row out of the wall is a row the query does
// not match, so it is NotFound -- that it exists is itself something not to
// say.
func Wall() bare.Scope { return wall{} }

// wall is what [Wall] answers with. It writes out every entity, including
// the ones that are not behind the wall, so that an entity added to the
// schema cannot arrive without a decision having been made about it.
type wall struct{}

var _ bare.Scope = wall{}

// CellScope: a row belongs to the tenant its "tenant" reaches.
func (wall) CellScope(ctx context.Context) (predicate.Cell, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return cell.HasTenantWith(tenant.IDIn(vs...)), nil
}

// FleetScope: declared `global`, so it is not behind the wall at all.
func (wall) FleetScope(ctx context.Context) (predicate.Fleet, error) {
	return nil, nil
}

// JointScope: a row belongs to the tenant its "robot.tenant" reaches.
func (wall) JointScope(ctx context.Context) (predicate.Joint, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return joint.HasRobotWith(robot.HasTenantWith(tenant.IDIn(vs...))), nil
}

// RobotScope: a row belongs to the tenant its "tenant" reaches.
func (wall) RobotScope(ctx context.Context) (predicate.Robot, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return robot.HasTenantWith(tenant.IDIn(vs...)), nil
}

// AuditScope: a row belongs to the tenant its "tenant_id" names, which it holds without an edge.
func (wall) AuditScope(ctx context.Context) (predicate.Audit, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return audit.TenantIDIn(vs...), nil
}

// HolderScope: a row belongs to the tenant its "tenant" reaches.
func (wall) HolderScope(ctx context.Context) (predicate.Holder, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return holder.HasTenantWith(tenant.IDIn(vs...)), nil
}

// TenantScope: a tenant is inside itself, which is what a tenant being a wall comes down to.
func (wall) TenantScope(ctx context.Context) (predicate.Tenant, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return tenant.IDIn(vs...), nil
}
