// Code generated by protoc-gen-pd. DO NOT EDIT.

// Package pd is what the schema said, as code.
//
// Nothing here is a decision. Every line follows from a `(payday.entity)`
// option, and the reason it is generated rather than written is that the
// line nobody writes is the one that matters -- an entity added to the
// schema arrives here with its wall already on it.
package pd

import (
	context "context"
	dialect "entgo.io/ent/dialect"
	uuid "github.com/google/uuid"
	audit1 "github.com/lesomnus/payday/audit"
	frame "github.com/lesomnus/payday/frame"
	gate "github.com/lesomnus/payday/gate"
	apptest "github.com/lesomnus/payday/internal/apptest"
	ent "github.com/lesomnus/payday/internal/apptest/ent"
	audit "github.com/lesomnus/payday/internal/apptest/ent/audit"
	cell "github.com/lesomnus/payday/internal/apptest/ent/cell"
	holder "github.com/lesomnus/payday/internal/apptest/ent/holder"
	joint "github.com/lesomnus/payday/internal/apptest/ent/joint"
	predicate "github.com/lesomnus/payday/internal/apptest/ent/predicate"
	robot "github.com/lesomnus/payday/internal/apptest/ent/robot"
	tenant "github.com/lesomnus/payday/internal/apptest/ent/tenant"
	bare "github.com/lesomnus/payday/internal/apptest/server/bare"
	pdid "github.com/lesomnus/payday/pdid"
	watch "github.com/lesomnus/payday/watch"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	entpage "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpage"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	slices "slices"
	time "time"
)

// The domain of each entity, as declared by `(payday.entity).domain`.
//
// A domain outlives the row it named: an identifier read out of an audit
// trail says what kind of thing it was long after the row is gone. So a
// number is chosen once and never given to something else.
const (
	CellDomain   pdid.Domain = 10 // "cell"
	FleetDomain  pdid.Domain = 9  // "fleet"
	JointDomain  pdid.Domain = 8  // "joint"
	RobotDomain  pdid.Domain = 7  // "robot"
	AuditDomain  pdid.Domain = 3  // "audit"
	HolderDomain pdid.Domain = 2  // "holder"
	TenantDomain pdid.Domain = 1  // "tenant"
)

func init() {
	pdid.Register("app.Cell", CellDomain, "cell")
	pdid.Register("app.Fleet", FleetDomain, "fleet")
	pdid.Register("app.Joint", JointDomain, "joint")
	pdid.Register("app.Robot", RobotDomain, "robot")
	pdid.Register("payday.Audit", AuditDomain, "audit")
	pdid.Register("payday.Holder", HolderDomain, "holder")
	pdid.Register("payday.Tenant", TenantDomain, "tenant")
}

// Domains is the domain of each entity by the full name of its message,
// which is the name a [Minter] is asked about.
var Domains = map[string]pdid.Domain{
	"app.Cell":      CellDomain,
	"app.Fleet":     FleetDomain,
	"app.Joint":     JointDomain,
	"app.Robot":     RobotDomain,
	"payday.Audit":  AuditDomain,
	"payday.Holder": HolderDomain,
	"payday.Tenant": TenantDomain,
}

// Minter answers with the [bare.Minter] that gives every new row an
// identifier of its entity's domain, and refuses one of another.
//
// It is asked by name because that is what the generated servers know
// themselves by; an entity nothing declared is refused rather than given
// an identifier that says nothing.
func Minter() bare.Minter {
	return bare.MinterFunc(func(
		_ context.Context, entity string, given uuid.UUID, ok bool,
	) (uuid.UUID, error) {
		d, found := Domains[entity]
		if !found {
			return uuid.Nil, pdid.NoDomain(entity)
		}

		return pdid.Mint(d, given, ok)
	})
}

// Wall answers with the scope that puts every read behind the tenant the
// row belongs to.
//
// It is installed on the innermost server rather than applied in front,
// which reads backwards and is the point: narrowing what a caller may see
// is a predicate, and a predicate belongs in the query. Done from in front
// it is an override of Get, Patch, Apply and Erase, once per entity and
// once more for every entity added afterwards.
//
//	sink, err := bare.NewServer(db, bare.WithScope(pd.Wall()))
//
// Narrowing is not refusing. A row out of the wall is a row the query does
// not match, so it is NotFound -- that it exists is itself something not to
// say.
func Wall() bare.Scope { return wall{} }

// wall is what [Wall] answers with. It writes out every entity, including
// the ones that are not behind the wall, so that an entity added to the
// schema cannot arrive without a decision having been made about it.
type wall struct{}

var _ bare.Scope = wall{}

// CellScope: a row belongs to the tenant its "tenant" reaches.
func (wall) CellScope(ctx context.Context) (predicate.Cell, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return cell.HasTenantWith(tenant.IDIn(vs...)), nil
}

// FleetScope: declared `global`, so it is not behind the wall at all.
func (wall) FleetScope(ctx context.Context) (predicate.Fleet, error) {
	return nil, nil
}

// JointScope: a row belongs to the tenant its "robot.tenant" reaches.
func (wall) JointScope(ctx context.Context) (predicate.Joint, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return joint.HasRobotWith(robot.HasTenantWith(tenant.IDIn(vs...))), nil
}

// RobotScope: a row belongs to the tenant its "tenant" reaches.
func (wall) RobotScope(ctx context.Context) (predicate.Robot, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return robot.HasTenantWith(tenant.IDIn(vs...)), nil
}

// AuditScope: a row belongs to the tenant its "tenant_id" names, which it holds without an edge.
func (wall) AuditScope(ctx context.Context) (predicate.Audit, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return audit.TenantIDIn(vs...), nil
}

// HolderScope: a row belongs to the tenant its "tenant" reaches.
func (wall) HolderScope(ctx context.Context) (predicate.Holder, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return holder.HasTenantWith(tenant.IDIn(vs...)), nil
}

// TenantScope: a tenant is inside itself, which is what a tenant being a wall comes down to.
func (wall) TenantScope(ctx context.Context) (predicate.Tenant, error) {
	vs, all, err := frame.Narrow(ctx)
	if all || err != nil {
		return nil, err
	}

	return tenant.IDIn(vs...), nil
}

// Sink is the server the stack is built on: the generated CRUD servers,
// with a List on every entity that declared one.
//
// A list belongs here and not in a layer in front for the reason the wall
// does: it is the read the generated servers do not make, so nothing else
// narrows it -- and a list cut short at a limit and filtered afterwards is
// one that any tenant can push another's rows out of by making enough of
// its own.
//
//	sink, err := pd.NewSink(db, bare.WithMinter(pd.Minter()), bare.WithScope(pd.Wall()))
type Sink struct {
	bare.Server

	// w is what a Watch listens on, and is nil for a deployment that
	// serves none. It is here rather than on the generated Store because
	// that struct is the ORM generator's and knows nothing about payday.
	w *watch.Watch
}

func NewSink(db *ent.Client, opts ...bare.Option) (Sink, error) {
	v, err := bare.NewServer(db, opts...)
	if err != nil {
		return Sink{}, err
	}

	return Sink{Server: v}, nil
}

// WithWatch answers with this server publishing to `w`, which is what a
// Watch reads from. A server built without one serves no Watch.
func (s Sink) WithWatch(w *watch.Watch) Sink {
	s.w = w
	return s
}

var _ apptest.Server = Sink{}
var _ enttx.Binder[apptest.Server] = Sink{}

// WithDriver answers with this server running on `drv`; see [Gate.WithDriver].
func (s Sink) WithDriver(drv dialect.Driver) (apptest.Server, error) {
	v, err := s.Server.WithDriver(drv)
	if err != nil {
		return nil, err
	}

	return Sink{Server: v.(bare.Server), w: s.w}, nil
}

type sinkRobot struct {
	apptest.RobotServiceServer
	store bare.Store
	w     *watch.Watch
}

func (s Sink) Robot() apptest.RobotServiceServer {
	return sinkRobot{s.Server.Robot(), s.Server.Store, s.w}
}

// orderRobot is how Robots come back.
//
// The last column is the key, and it is not decoration: a cursor cannot
// tell apart two rows equal in every column of the order, so the page after
// the first of them either repeats the second or skips it. Rows written by
// one request are stamped a moment apart at best.
var orderRobot = []entpage.Order{
	{Column: robot.FieldDateCreated, Desc: false},
	{Column: robot.FieldID, Desc: false},
}

const (
	// RobotPageSize is what a request that did not say gets, and
	// RobotPageLimit is the most it gets however loudly it asks.
	RobotPageSize  = 50
	RobotPageLimit = 100

	// RobotFilterLimit is how many filters one request may carry. Each is a
	// predicate in the same query, so it is what says how much of the
	// database a request may ask to read -- and it is refused rather than
	// clamped, because dropping half the filters would answer a question
	// nobody asked.
	RobotFilterLimit = 32
)

// List answers with the Robots that match any of the given filters, or with
// every one there is if the request named none, a page at a time.
func (s sinkRobot) List(ctx context.Context, req *apptest.RobotListRequest) (*apptest.RobotListResponse, error) {
	q := s.store.Db.Robot.Query()

	// Through the same narrowing every generated read goes through, and not
	// by asking the scope alone: what narrows a read is the wall today and
	// the wall and something else tomorrow, and a list that reached past it
	// would be the one read that missed the something else.
	if p, err := bare.RobotNarrow(ctx, s.store.Scope, nil); err != nil {
		return nil, err
	} else if p != nil {
		q.Where(p)
	}

	if fs := req.GetFilters(); len(fs) > 0 {
		if len(fs) > RobotFilterLimit {
			return nil, status.Errorf(codes.InvalidArgument,
				"filters: %d of them, and %d is the most one list carries", len(fs), RobotFilterLimit)
		}

		ps := make([]predicate.Robot, 0, len(fs))
		for i, f := range fs {
			p, err := filterRobot(f)
			if err != nil {
				return nil, status.Errorf(codes.InvalidArgument, "filters[%d]: %s", i, err)
			}

			ps = append(ps, p)
		}

		q.Where(robot.Or(ps...))
	}

	if v := req.GetAfter(); v != "" {
		var (
			at0 time.Time
			at1 uuid.UUID
		)
		if err := entpage.Decode(v, &at0, &at1); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "after: %s", err)
		}

		p, err := entpage.After(orderRobot, []any{at0, at1})
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "after: %s", err)
		}

		q.Where(p)
	}

	q.WithTenant()

	// One row more than the page, which is how "is there another" is answered
	// without a second query and without a count. The extra is dropped before
	// the answer is built; it was only ever asked for to see whether it was
	// there -- so a full last page answers with no cursor rather than sending
	// the caller back for an empty one.
	size := entpage.Size(int(req.GetSize()), RobotPageSize, RobotPageLimit)
	us, err := q.Order(robot.ByDateCreated(), robot.ByID()).Limit(size + 1).All(ctx)
	if err != nil {
		return nil, err
	}

	more := len(us) > size
	if more {
		us = us[:size]
	}

	items := make([]*apptest.Robot, len(us))
	for i, u := range us {
		items[i] = u.Proto()
	}

	res := apptest.RobotListResponse_builder{Items: items}.Build()
	if more {
		last := us[len(us)-1]
		next, err := entpage.Encode(last.DateCreated, last.ID)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "next: %s", err)
		}

		res.SetNext(next)
	}

	return res, nil
}

// filterRobot turns one filter into the predicate that selects what it
// names. Naming nothing is refused, since the request asked for "these" and
// did not say which.
func filterRobot(f *apptest.RobotFilter) (predicate.Robot, error) {
	ps := make([]predicate.Robot, 0, 1)
	if f.HasRef() {
		p, err := bare.RobotPick(f.GetRef())
		if err != nil {
			return nil, err
		}

		ps = append(ps, p)
	}
	if len(ps) == 0 {
		return nil, status.Error(codes.InvalidArgument, "a filter that names nothing")
	}

	return robot.And(ps...), nil
}

// RobotService is the prefix of every RPC of that service, which is how a
// change is known to be about a Robot. A service is named for the entity it
// is about, so the name carries it.
var RobotService = watch.ServiceOf(apptest.RobotService_Get_FullMethodName)

// Watch answers with the Robots this caller may see, as they are now and as
// they change.
//
// What is sent is **state and never a delta**, which is what makes a stream
// that missed something still correct: the next item about a row carries the
// whole of it, so a client converges rather than replays. It is also what
// makes the first message safe to duplicate against the ones after it.
func (s sinkRobot) Watch(req *apptest.RobotWatchRequest, out grpc.ServerStreamingServer[apptest.RobotWatchResponse]) error {
	ctx := out.Context()

	// A watch with no filters is the whole table, forever. It is the one
	// shape that has no cap at all, so it is the one shape refused.
	fs := req.GetFilters()
	switch {
	case len(fs) == 0:
		return status.Error(codes.InvalidArgument,
			"filters: a watch says which rows it is about; one that says nothing is the whole table, for as long as it is open")
	case len(fs) > RobotFilterLimit:
		return status.Errorf(codes.InvalidArgument,
			"filters: %d of them, and %d is the most one watch carries", len(fs), RobotFilterLimit)
	}

	// Resolved before anything is subscribed to, so a name that names
	// nothing is an answer rather than a stream that quietly watches none.
	watching, err := s.watchRobotKeys(ctx, fs)
	if err != nil {
		return err
	}

	var snapshot func(watch.Seen) error
	if !req.GetSkipSnapshot() {
		snapshot = func(sent watch.Seen) error { return s.watchNow(ctx, req, out, sent) }
	}

	if s.w == nil {
		return status.Error(codes.Unimplemented,
			"this deployment publishes no changes; see WithWatch")
	}

	return watch.Stream(ctx, s.w, RobotService, snapshot,
		func(ks map[pdid.Id]string, sent watch.Seen) error {
			items := make([]*apptest.RobotWatchItem, 0, len(ks))
			for k, action := range ks {
				u, err := s.watchRead(ctx, watching, k)
				if err != nil {
					return err
				}
				if u == nil && !sent[k] {
					// Not theirs, or not what they asked for, and they
					// have never been told about it. A row that never
					// matched is not news.
					continue
				}

				sent[k] = u != nil
				items = append(items, apptest.RobotWatchItem_builder{
					Id:     k.Bytes(),
					Value:  u,
					Action: action,
				}.Build())
			}
			if len(items) == 0 {
				return nil
			}

			return out.Send(apptest.RobotWatchResponse_builder{Items: items}.Build())
		})
}

// watchNow sends what matches right now, through the same List a caller
// would have called -- so what a stream begins with and what a list answers
// cannot disagree, and a client does not have to do both and race them.
func (s sinkRobot) watchNow(
	ctx context.Context, req *apptest.RobotWatchRequest, out grpc.ServerStreamingServer[apptest.RobotWatchResponse],
	sent watch.Seen,
) error {
	after := ""
	for {
		res, err := s.List(ctx, apptest.RobotListRequest_builder{
			Filters: req.GetFilters(),
			After:   after,
		}.Build())
		if err != nil {
			return err
		}

		items := make([]*apptest.RobotWatchItem, 0, len(res.GetItems()))
		for _, u := range res.GetItems() {
			k, err := pdid.From(u.GetId())
			if err != nil {
				return err
			}

			sent[k] = true
			// No action: this is not something anybody asked for, it is
			// what is already there.
			items = append(items, apptest.RobotWatchItem_builder{Id: u.GetId(), Value: u}.Build())
		}
		if len(items) > 0 {
			if err := out.Send(apptest.RobotWatchResponse_builder{Items: items}.Build()); err != nil {
				return err
			}
		}

		if after = res.GetNext(); after == "" {
			return nil
		}
	}
}

// watchRead answers with the row as it is now, or nil when it is no longer
// one this caller may see -- erased, walled off, or no longer matching what
// they asked for. The three are deliberately indistinguishable to a caller:
// a stream that told them apart would be saying which rows stopped being
// theirs, which is the thing the wall is for.
//
// The Get is what keeps the wall out of this file. It goes through the same
// server every other read does, with the context of the caller who asked, so
// a row they may not see comes back NotFound and is never sent.
func (s sinkRobot) watchRead(
	ctx context.Context, watching []pdid.Id, k pdid.Id,
) (*apptest.Robot, error) {
	// Not one of the rows this stream is about. Asked before the read, so a
	// busy table costs a stream nothing for the rows it does not watch.
	if !slices.Contains(watching, k) {
		return nil, nil
	}

	v, err := s.Get(ctx, apptest.RobotGetRequest_builder{
		Ref: apptest.RobotRef_builder{Id: k.Bytes()}.Build(),
	}.Build())
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}

		return nil, err
	}

	return v, nil
}

// watchRobotKeys is the rows a stream is about, resolved once when it opens.
//
// A filter names a row and a row is named several ways -- by identifier, or
// by whatever unique index the schema declared. Resolving them here rather
// than comparing them per event does three things: the comparison afterwards
// is an identifier against an identifier, a name that names nothing is
// refused when the stream opens rather than silently watching nothing, and a
// row renamed while the stream is open goes on being the row that was asked
// for -- which is what somebody watching a thing meant.
func (s sinkRobot) watchRobotKeys(
	ctx context.Context, fs []*apptest.RobotFilter,
) ([]pdid.Id, error) {
	ks := make([]pdid.Id, 0, len(fs))
	for i, f := range fs {
		if !f.HasRef() {
			return nil, status.Errorf(codes.InvalidArgument,
				"filters[%d]: a watch says which rows it is about by naming them", i)
		}

		v, err := s.Get(ctx, apptest.RobotGetRequest_builder{Ref: f.GetRef()}.Build())
		if err != nil {
			return nil, err
		}

		k, err := pdid.From(v.GetId())
		if err != nil {
			return nil, err
		}

		ks = append(ks, k)
	}

	return ks, nil
}

// Gate is the layer that says what a caller may do with a request.
//
// It goes outermost, so nothing behind it has to ask again -- though most
// of what it stands for is not enforced here at all: the wall is a
// predicate and predicates belong in the query, so [Wall] is installed on
// the innermost server. What is left is the two rules that are about a
// row which does not exist yet.
//
//	s, err := app.Build(walled, core.Build(), pd.AuditBuild(), pd.GateBuild())
type Gate struct {
	apptest.Overlay
}

func NewGate(next apptest.Server) Gate {
	return Gate{apptest.NewOverlay(next)}
}

var _ apptest.Server = Gate{}

var _ enttx.Binder[apptest.Server] = Gate{}

// WithDriver answers with this stack running on `drv`, which is how several
// servers are put on one transaction.
//
// Every layer writes this and none can inherit it: an overlay holds what is
// behind it and has no way to make itself again, so a layer that did not
// write it would be missing from the rebuilt stack and the requests inside
// the transaction would go around it.
func (s Gate) WithDriver(drv dialect.Driver) (apptest.Server, error) {
	next, err := enttx.Rebind(s.Next(), drv)
	if err != nil {
		return nil, err
	}

	return NewGate(next), nil
}

// GateBuild makes a builder of this layer so that it can be stacked.
func GateBuild() apptest.Builder { return gateBuilder{} }

type gateBuilder struct{}

func (gateBuilder) Build(next apptest.Server) (apptest.Server, error) {
	return NewGate(next), nil
}

type gateTenant struct {
	Gate
	apptest.TenantServiceServer
}

func (s Gate) Tenant() apptest.TenantServiceServer {
	return gateTenant{s, s.Next().Tenant()}
}

// Add is not served. A tenant is put up by whoever runs the deployment,
// through a server this layer is not in front of.
func (s gateTenant) Add(ctx context.Context, req *apptest.TenantAddRequest) (*apptest.Tenant, error) {
	return nil, gate.ErrDeployment("put up")
}

// Erase is not served either, and it would take everything in the tenant
// with it.
func (s gateTenant) Erase(ctx context.Context, req *apptest.TenantRef) (*emptypb.Empty, error) {
	return nil, gate.ErrDeployment("taken down")
}

type gateHolder struct {
	Gate
	apptest.HolderServiceServer
}

func (s Gate) Holder() apptest.HolderServiceServer {
	return gateHolder{s, s.Next().Holder()}
}

// Add is the one thing about a holder this layer still says, and it is here
// because it is the one that is not a predicate: the row does not exist yet,
// so there is nothing to narrow. Reading one, changing one and erasing one
// are all the wall.
//
// The check is a read of the tenant **through the wall** rather than a
// comparison against the scope, which costs a query and is worth it. A
// reference names a tenant by identifier or by alias, and answering "is this
// one of mine" without a query means holding every tenant in scope in full --
// fine while that is the caller's own and wrong as soon as it is a list a
// credential or a policy narrowed to.
//
// NotFound and not a refusal, which is the same answer every other read of a
// tenant gives: that one exists is itself something a caller who may not see
// it should not be told. It also gets a tenant that simply is not there
// right, which comparing against a scope did not.
func (s gateHolder) Add(ctx context.Context, req *apptest.HolderAddRequest) (*apptest.Holder, error) {
	if _, err := gate.Actor(ctx); err != nil {
		return nil, err
	}

	if _, err := s.Gate.Next().Tenant().Get(ctx, apptest.TenantGetRequest_builder{
		Ref: req.GetTenant(),
	}.Build()); err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, gate.ErrNotFound("Tenant")
		}

		return nil, err
	}

	return s.HolderServiceServer.Add(ctx, req)
}

// Audit is the layer that refuses a trail row written by hand.
//
// The RPCs exist because the trail is an entity like any other and a test is
// far plainer for having them. A deployment serves none of the ones that
// write: a trail somebody can edit is evidence of nothing.
type Audit struct {
	apptest.Overlay
}

func NewAudit(next apptest.Server) Audit {
	return Audit{apptest.NewOverlay(next)}
}

var _ apptest.Server = Audit{}
var _ enttx.Binder[apptest.Server] = Audit{}

// WithDriver answers with this stack running on `drv`; see [Gate.WithDriver].
func (s Audit) WithDriver(drv dialect.Driver) (apptest.Server, error) {
	next, err := enttx.Rebind(s.Next(), drv)
	if err != nil {
		return nil, err
	}

	return NewAudit(next), nil
}

// AuditBuild makes a builder of this layer so that it can be stacked.
func AuditBuild() apptest.Builder { return auditBuilder{} }

type auditBuilder struct{}

func (auditBuilder) Build(next apptest.Server) (apptest.Server, error) {
	return NewAudit(next), nil
}

type auditService struct {
	Audit
	apptest.AuditServiceServer
}

func (s Audit) Audit() apptest.AuditServiceServer {
	return auditService{s, s.Next().Audit()}
}

func (s auditService) Add(ctx context.Context, req *apptest.AuditAddRequest) (*apptest.Audit, error) {
	return nil, errTrail()
}

func (s auditService) Patch(ctx context.Context, req *apptest.AuditPatchRequest) (*apptest.Audit, error) {
	return nil, errTrail()
}

func (s auditService) Apply(ctx context.Context, req *apptest.AuditApplyRequest) (*apptest.Audit, error) {
	return nil, errTrail()
}

func (s auditService) Erase(ctx context.Context, req *apptest.AuditRef) (*emptypb.Empty, error) {
	return nil, errTrail()
}

// errTrail is Unimplemented and not PermissionDenied, and to everybody: it
// is not about who is asking, and no credential changes it.
func errTrail() error {
	return status.Error(codes.Unimplemented,
		"the trail is written by what happened, not by anybody asking")
}

// Recorder writes one row of the trail for every write the generated
// servers make.
//
// It is not a layer and it does not override an RPC. The servers call it
// from inside the transaction that makes the write, so the row and the
// record of it hold or fall together -- and so every RPC that changes
// anything is on the trail without anybody having listed them.
//
//	sink, err := bare.NewServer(db, bare.WithRecorder(pd.Recorder()))
func Recorder() bare.Recorder { return recorder{} }

type recorder struct{}

var _ bare.Recorder = recorder{}

// Record writes what happened. It runs inside the write's transaction, so an
// error here takes the write with it -- which is the answer wanted: a write
// that could not be accounted for did not happen.
//
// It writes through the server it was handed, which runs on that transaction
// and does not record; a recorder that recorded its own writes would not
// stop.
func (recorder) Record(ctx context.Context, s bare.Server, c bare.Change) error {
	var patch proto.Message
	if c.Patch != nil {
		patch = c.Patch
	}

	v, err := audit1.Of(ctx, c.Method, c.Key, patch)
	if err != nil {
		return err
	}

	_, err = s.Audit().Add(ctx, apptest.AuditAddRequest_builder{
		TenantId: v.Tenant.Bytes(),
		ActorId:  v.Actor.Bytes(),
		TraceId:  v.Trace,
		Action:   v.Action,
		ObjectId: v.Object.Bytes(),
		Patch:    v.Patch,
	}.Build())

	return err
}

var _ *patchpb.Patch

// WatchRecorder answers with the recorder that remembers a write for `w`.
//
// It is the other end of the hook the trail hangs off, and it wants the
// opposite thing from that moment: a trail row has to hold or fall with the
// write, so it is written there and then; an event has to be published only
// if the write survived, so nothing is published here at all.
//
//	sink, err := pd.NewSink(db, bare.WithRecorder(pd.WatchRecorder(w)))
func WatchRecorder(w *watch.Watch) bare.Recorder {
	return watchRecorder{w}
}

type watchRecorder struct {
	w *watch.Watch
}

var _ bare.Recorder = watchRecorder{}

func (r watchRecorder) Record(ctx context.Context, _ bare.Server, c bare.Change) error {
	k, err := pdid.From(keyBytes(c.Key))
	if err != nil {
		// A key this app does not make. Nothing to publish about it, and
		// nothing worth failing a write for.
		return nil
	}

	var doc []byte
	if c.Patch != nil {
		if b, err := proto.Marshal(c.Patch); err == nil {
			doc = b
		}
	}

	r.w.Note(ctx, watch.Change{
		Method: c.Method,
		By:     c.By,
		Key:    k,
		Patch:  doc,
	})

	return nil
}

// keyBytes is a key as the sixteen bytes an identifier is.
func keyBytes(v any) []byte {
	switch u := v.(type) {
	case uuid.UUID:
		return u[:]
	case [16]byte:
		return u[:]
	}

	return nil
}
